In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
https://fbref.com/en/players/e46012d4/matchlogs/2024-2025/Kevin-De-Bruyne-Match-Logs

In [334]:
test = pd.read_html('https://fbref.com/en/players/e46012d4/matchlogs/2024-2025/Kevin-De-Bruyne-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [336]:
test.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-07-01                Mon            UEFA Euro
1         2024-08-10                Sat  FA Community Shield
2         2024-08-18                Sun       Premier League
3         2024-08-24                Sat       Premier League
4         2024-08-31                Sat       Premier League

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                 Round              Venue             Result
0          Round of 16            Neutral              L 0–1
1  FA Community Shield               Home      D 1 (7)–1 (6)
2          Matchweek 1               Away              W 2–0
3          Matchweek 2               Home              W 4–1
4          Matchweek 3               Away              W 3–1

  Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  \
               Squad           Opponent              Start                Pos
0         be Belgium          fr France                 Y*              CM,AM
1    Manchester City     Manchester Utd                  N                NaN
2    Manchester City            Chelsea                 Y*                 CM
3    Manchester City       Ipswich Town                 Y*              CM,AM
4    Manchester City           West Ham                 Y*                 CM

   ...  SCA Passes                 Carries      Take-Ons       \
   ...  GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0  ...    0     44   53  83.0    6      37    0        2    1
1  ...  NaN    NaN  NaN   NaN  NaN     NaN  NaN      NaN  NaN
2  ...    0     46   58  79.3    5      33    4        2    1
3  ...    1     86  104  82.7   16      61    4        1    1
4  ...    0     75   95  78.9   12      50    2        3    2

  Unnamed: 36_level_0
         Match Report
0        Match Report
1        Match Report
2        Match Report
3        Match Report
4        Match Report

[5 rows x 37 columns]

In [338]:
player_cols = pd.DataFrame()
player_cols['Date'] = test['Unnamed: 0_level_0']['Date'].copy()

In [340]:
player_cols.head()

         Date
0  2024-07-01
1  2024-08-10
2  2024-08-18
3  2024-08-24
4  2024-08-31

In [342]:
player_cols['Competition'] = test['Unnamed: 2_level_0']['Comp'].copy()
player_cols['Opponent'] = test['Unnamed: 7_level_0']['Opponent'].copy()

In [344]:
player_cols.head()

         Date          Competition        Opponent
0  2024-07-01            UEFA Euro       fr France
1  2024-08-10  FA Community Shield  Manchester Utd
2  2024-08-18       Premier League         Chelsea
3  2024-08-24       Premier League    Ipswich Town
4  2024-08-31       Premier League        West Ham

In [346]:
player_cols['Player'] = "Kevin De Bruyne"

In [348]:
player_cols.head()

         Date          Competition        Opponent           Player
0  2024-07-01            UEFA Euro       fr France  Kevin De Bruyne
1  2024-08-10  FA Community Shield  Manchester Utd  Kevin De Bruyne
2  2024-08-18       Premier League         Chelsea  Kevin De Bruyne
3  2024-08-24       Premier League    Ipswich Town  Kevin De Bruyne
4  2024-08-31       Premier League        West Ham  Kevin De Bruyne

In [350]:
player_cols['Started the Game'] = test['Unnamed: 8_level_0']['Start'].copy()
player_cols['Position'] = test['Unnamed: 9_level_0']['Pos'].copy()
player_cols['Minutes'] = test['Unnamed: 10_level_0']['Min'].copy()
player_cols['Venue'] = test['Unnamed: 4_level_0']['Venue'].copy()
player_cols['Result'] = test['Unnamed: 5_level_0']['Result'].copy()

In [352]:
player_cols = player_cols.dropna(subset=['Date'])
player_cols

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-01,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1
1,2024-08-10,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NaN,1,Home,D 1 (7)–1 (6)
2,2024-08-18,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0
3,2024-08-24,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1
4,2024-08-31,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1
5,2024-09-06,UEFA Nations League,il Israel,Kevin De Bruyne,Y*,AM,90,Home,W 3–1
6,2024-09-09,UEFA Nations League,fr France,Kevin De Bruyne,Y*,AM,90,Away,L 0–2
7,2024-09-14,Premier League,Brentford,Kevin De Bruyne,Y,AM,90,Home,W 2–1
8,2024-09-18,Champions Lg,it Inter,Kevin De Bruyne,Y*,CM,45,Home,D 0–0
10,2024-11-02,Premier League,Bournemouth,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,L 1–2
11,2024-11-05,Champions Lg,pt Sporting CP,Kevin De Bruyne,N,CM,7,Away,L 1–4
12,2024-11-09,Premier League,Brighton,Kevin De Bruyne,N,CM,17,Away,L 1–2
13,2024-11-23,Premier League,Tottenham,Kevin De Bruyne,N,CM,17,Home,L 0–4
14,2024-11-26,Champions Lg,nl Feyenoord,Kevin De Bruyne,N,AM,23,Home,D 3–3
15,2024-12-01,Premier League,Liverpool,Kevin De Bruyne,N,"CM,AM",12,Away,L 0–2
16,2024-12-04,Premier League,Nott'ham Forest,Kevin De Bruyne,Y*,AM,73,Home,W 3–0
17,2024-12-07,Premier League,Crystal Palace,Kevin De Bruyne,Y,AM,85,Away,D 2–2
18,2024-12-11,Champions Lg,it Juventus,Kevin De Bruyne,Y,"AM,CM",90,Away,L 0–2
19,2024-12-15,Premier League,Manchester Utd,Kevin De Bruyne,Y,CM,67,Home,L 1–2
20,2024-12-21,Premier League,Aston Villa,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,L 1–2
21,2024-12-26,Premier League,Everton,Kevin De Bruyne,N,CM,16,Home,D 1–1
22,2024-12-29,Premier League,Leicester City,Kevin De Bruyne,Y*,CM,90,Away,W 2–0
23,2025-01-04,Premier League,West Ham,Kevin De Bruyne,Y*,CM,90,Home,W 4–1
24,2025-01-11,FA Cup,Salford City,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Home,W 8–0
25,2025-01-14,Premier League,Brentford,Kevin De Bruyne,Y*,AM,90,Away,D 2–2
26,2025-01-19,Premier League,Ipswich Town,Kevin De Bruyne,Y*,AM,62,Away,W 6–0
27,2025-01-22,Champions Lg,fr Paris S-G,Kevin De Bruyne,Y*,AM,69,Away,L 2–4
28,2025-01-25,Premier League,Chelsea,Kevin De Bruyne,N,LW,17,Home,W 3–1
29,2025-01-29,Champions Lg,be Club Brugge,Kevin De Bruyne,Y*,AM,80,Home,W 3–1
30,2025-02-02,Premier League,Arsenal,Kevin De Bruyne,N,AM,19,Away,L 1–5
31,2025-02-08,FA Cup,Leyton Orient,Kevin De Bruyne,N,NaN,19,Away,W 2–1
32,2025-02-11,Champions Lg,es Real Madrid,Kevin De Bruyne,Y*,"CM,AM",83,Home,L 2–3
33,2025-02-15,Premier League,Newcastle Utd,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Home,W 4–0
34,2025-02-19,Champions Lg,es Real Madrid,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,L 1–3
35,2025-02-23,Premier League,Liverpool,Kevin De Bruyne,Y*,CM,65,Home,L 0–2
36,2025-02-26,Premier League,Tottenham,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,W 1–0
37,2025-03-01,FA Cup,Plymouth Argyle,Kevin De Bruyne,Y*,AM,90,Home,W 3–1
38,2025-03-08,Premier League,Nott'ham Forest,Kevin De Bruyne,N,CM,22,Away,L 0–1
39,2025-03-15,Premier League,Brighton,Kevin De Bruyne,N,AM,5,Home,D 2–2
40,2025-03-20,UEFA Nations League,ua Ukraine,Kevin De Bruyne,Y,AM,69,Away,L 1–3
41,2025-03-23,UEFA Nations League,ua Ukraine,Kevin De Bruyne,Y*,CM,90,Home,W 3–0
42,2025-03-30,FA Cup,Bournemouth,Kevin De Bruyne,Y*,FW,90,Away,W 2–1
43,2025-04-02,Premier League,Leicester City,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Home,W 2–0
44,2025-04-06,Premier League,Manchester Utd,Kevin De Bruyne,Y*,AM,90,Away,D 0–0
45,2025-04-12,Premier League,Crystal Palace,Kevin De Bruyne,Y*,FW,86,Home,W 5–2
46,2025-04-19,Premier League,Everton,Kevin De Bruyne,Y*,AM,87,Away,W 2–0
47,2025-04-22,Premier League,Aston Villa,Kevin De Bruyne,Y*,FW,89,Home,W 2–1
48,2025-04-27,FA Cup,Nott'ham Forest,Kevin De Bruyne,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,W 2–0
49,2025-05-02,Premier League,Wolves,Kevin De Bruyne,Y*,FW,83,Home,W 1–0
50,2025-05-10,Premier League,Southampton,Kevin De Bruyne,Y*,"CM,AM",90,Away,D 0–0
51,2025-05-17,FA Cup,Crystal Palace,Kevin De Bruyne,Y*,DM,90,Neutral,L 0–1
52,2025-05-20,Premier League,Bournemouth,Kevin De Bruyne,Y*,AM,68,Home,W 3–1
53,2025-05-25,Premier League,Fulham,Kevin De Bruyne,N,AM,6,Away,W 2–0
54,2025-06-06,WCQ,mk N. Macedonia,Kevin De Bruyne,Y,CM,55,Away,D 1–1
55,2025-06-09,WCQ,wls Wales,Kevin De Bruyne,Y,AM,88,Home,W 4–3

In [354]:
player_cols.loc[player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
player_cols["Date"] = pd.to_datetime(player_cols["Date"], format="%Y-%m-%d")

player_cols.sort_values(by=["Player","Date"])

player_cols["7D Rolling Avg"] = player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
player_cols["14D Rolling Avg"] = player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [356]:
player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0
1,2024-08-10,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NaN,1,Home,D 1 (7)–1 (6),1.0,1.0
2,2024-08-18,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0
3,2024-08-24,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0
4,2024-08-31,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0

In [478]:
test_mc = pd.read_html('https://fbref.com/en/players/16264a81/matchlogs/2024-2025/Moises-Caicedo-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [480]:
test_mc.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Date                Day               Comp              Round
0         2024-07-04                Thu       Copa América     Quarter-finals
1         2024-08-18                Sun     Premier League        Matchweek 1
2         2024-08-22                Thu            Conf Lg     Play-off round
3         2024-08-25                Sun     Premier League        Matchweek 2
4         2024-08-29                Thu            Conf Lg     Play-off round

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Venue             Result              Squad           Opponent
0            Neutral      D 1 (2)–1 (4)         ec Ecuador       ar Argentina
1               Home              L 0–2            Chelsea    Manchester City
2               Home              W 2–0        eng Chelsea     ch Servette FC
3               Away              W 6–2            Chelsea             Wolves
4               Away              L 1–2        eng Chelsea     ch Servette FC

  Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes                  \
               Start                Pos  ...  GCA    Cmp  Att  Cmp% PrgP
0                  Y           AM,CM,DM  ...    1     36   48  75.0    9
1                  Y                 DM  ...    0     47   53  88.7    3
2                 Y*                 CM  ...  NaN    NaN  NaN   NaN  NaN
3                  Y                 DM  ...    1     32   37  86.5    3
4                  N                NaN  ...  NaN    NaN  NaN   NaN  NaN

  Carries      Take-Ons      Unnamed: 36_level_0
  Carries PrgC      Att Succ        Match Report
0      34    1        2    0        Match Report
1      34    0        1    1        Match Report
2     NaN  NaN      NaN  NaN        Match Report
3      23    1        2    1        Match Report
4     NaN  NaN      NaN  NaN        Match Report

[5 rows x 37 columns]

In [482]:
test_mc.columns = test_mc.columns.get_level_values(1)

In [486]:
test_mc["Date"] = pd.to_datetime(test_mc["Date"], format="%Y-%m-%d",yearfirst=True)

In [484]:
mc_player_cols = pd.DataFrame()

In [488]:
mc_player_cols['Date'] = test_mc['Date'].copy()
mc_player_cols['Competition'] = test_mc['Comp'].copy()
mc_player_cols['Opponent'] = test_mc['Opponent'].copy()
mc_player_cols['Player'] = "Moises Caicedo"
mc_player_cols['Started the Game'] = test_mc['Start'].copy()
mc_player_cols['Position'] = test_mc['Pos'].copy()
mc_player_cols['Minutes'] = test_mc['Min'].copy()
mc_player_cols['Venue'] = test_mc['Venue'].copy()
mc_player_cols['Result'] = test_mc['Result'].copy()

In [490]:
mc_player_cols

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-04,Copa América,ar Argentina,Moises Caicedo,Y,"AM,CM,DM",90,Neutral,D 1 (2)–1 (4)
1,2024-08-18,Premier League,Manchester City,Moises Caicedo,Y,DM,90,Home,L 0–2
2,2024-08-22,Conf Lg,ch Servette FC,Moises Caicedo,Y*,CM,83,Home,W 2–0
3,2024-08-25,Premier League,Wolves,Moises Caicedo,Y,DM,75,Away,W 6–2
4,2024-08-29,Conf Lg,ch Servette FC,Moises Caicedo,N,NaN,28,Away,L 1–2
...,...,...,...,...,...,...,...,...,...
67,2025-06-16,Club World Cup,us LAFC,Moises Caicedo,Y,DM,82,Neutral,W 2–0
68,2025-06-20,Club World Cup,br Flamengo,Moises Caicedo,Y,DM,90,Neutral,L 1–3
69,2025-06-24,Club World Cup,tn Espérance Tunis,Moises Caicedo,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,W 3–0
70,2025-06-28,Club World Cup,pt Benfica,Moises Caicedo,Y,DM,120,Neutral,W 4–1
71,NaT,NaN,NaN,Moises Caicedo,56/58,NaN,5002,NaN,30-15-13

In [492]:
mc_player_cols = mc_player_cols.dropna(subset=['Date'])

In [494]:
mc_player_cols.loc[mc_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0

In [496]:
mc_player_cols.sort_values(by=["Player","Date"])

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-04,Copa América,ar Argentina,Moises Caicedo,Y,"AM,CM,DM",90,Neutral,D 1 (2)–1 (4)
1,2024-08-18,Premier League,Manchester City,Moises Caicedo,Y,DM,90,Home,L 0–2
2,2024-08-22,Conf Lg,ch Servette FC,Moises Caicedo,Y*,CM,83,Home,W 2–0
3,2024-08-25,Premier League,Wolves,Moises Caicedo,Y,DM,75,Away,W 6–2
4,2024-08-29,Conf Lg,ch Servette FC,Moises Caicedo,N,NaN,28,Away,L 1–2
...,...,...,...,...,...,...,...,...,...
66,2025-06-10,WCQ,pe Peru,Moises Caicedo,Y,CM,90,Away,D 0–0
67,2025-06-16,Club World Cup,us LAFC,Moises Caicedo,Y,DM,82,Neutral,W 2–0
68,2025-06-20,Club World Cup,br Flamengo,Moises Caicedo,Y,DM,90,Neutral,L 1–3
69,2025-06-24,Club World Cup,tn Espérance Tunis,Moises Caicedo,N,"On matchday squad, but did not play",0,Neutral,W 3–0
70,2025-06-28,Club World Cup,pt Benfica,Moises Caicedo,Y,DM,120,Neutral,W 4–1

In [498]:
mc_player_cols["7D Rolling Avg"] = mc_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
mc_player_cols["14D Rolling Avg"] = mc_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

C:\Users\Ganesh\AppData\Local\Temp\ipykernel_2908\2848271915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mc_player_cols["7D Rolling Avg"] = mc_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
C:\Users\Ganesh\AppData\Local\Temp\ipykernel_2908\2848271915.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mc_player_cols["14D Rolling Avg"] = mc_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [500]:
mc_player_cols

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-04,Copa América,ar Argentina,Moises Caicedo,Y,"AM,CM,DM",90,Neutral,D 1 (2)–1 (4),90.0,90.0
1,2024-08-18,Premier League,Manchester City,Moises Caicedo,Y,DM,90,Home,L 0–2,90.0,90.0
2,2024-08-22,Conf Lg,ch Servette FC,Moises Caicedo,Y*,CM,83,Home,W 2–0,173.0,173.0
3,2024-08-25,Premier League,Wolves,Moises Caicedo,Y,DM,75,Away,W 6–2,158.0,248.0
4,2024-08-29,Conf Lg,ch Servette FC,Moises Caicedo,N,NaN,28,Away,L 1–2,103.0,276.0
...,...,...,...,...,...,...,...,...,...,...,...
66,2025-06-10,WCQ,pe Peru,Moises Caicedo,Y,CM,90,Away,D 0–0,NaN,NaN
67,2025-06-16,Club World Cup,us LAFC,Moises Caicedo,Y,DM,82,Neutral,W 2–0,NaN,NaN
68,2025-06-20,Club World Cup,br Flamengo,Moises Caicedo,Y,DM,90,Neutral,L 1–3,NaN,NaN
69,2025-06-24,Club World Cup,tn Espérance Tunis,Moises Caicedo,N,"On matchday squad, but did not play",0,Neutral,W 3–0,NaN,NaN
70,2025-06-28,Club World Cup,pt Benfica,Moises Caicedo,Y,DM,120,Neutral,W 4–1,NaN,NaN

In [416]:
test_bg = pd.read_html('https://fbref.com/en/players/82518f62/matchlogs/2024-2025/Bruno-Guimaraes-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [418]:
test_bg.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Date                Day               Comp              Round
0         2024-07-02                Tue       Copa América        Group stage
1         2024-07-06                Sat       Copa América     Quarter-finals
2         2024-08-17                Sat     Premier League        Matchweek 1
3         2024-08-25                Sun     Premier League        Matchweek 2
4         2024-08-28                Wed            EFL Cup       Second round

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Venue             Result              Squad           Opponent
0            Neutral              D 1–1          br Brazil        co Colombia
1            Neutral      D 0 (2)–0 (4)          br Brazil         uy Uruguay
2               Home              W 1–0      Newcastle Utd        Southampton
3               Away              D 1–1      Newcastle Utd        Bournemouth
4               Away      D 1 (4)–1 (3)      Newcastle Utd    Nott'ham Forest

  Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes                    \
               Start                Pos  ...  GCA    Cmp   Att  Cmp%  PrgP
0                  Y                 DM  ...  1.0   44.0  48.0  91.7   6.0
1                  Y                 DM  ...  0.0   35.0  38.0  92.1   4.0
2                 Y*                 CM  ...  0.0   18.0  28.0  64.3   1.0
3                 Y*                 CM  ...  0.0   59.0  75.0  78.7  16.0
4                  N                NaN  ...  NaN    NaN   NaN   NaN   NaN

  Carries      Take-Ons      Unnamed: 36_level_0
  Carries PrgC      Att Succ        Match Report
0    42.0  1.0      2.0  2.0        Match Report
1    15.0  1.0      1.0  0.0        Match Report
2    17.0  0.0      0.0  0.0        Match Report
3    56.0  4.0      1.0  1.0        Match Report
4     NaN  NaN      NaN  NaN        Match Report

[5 rows x 37 columns]

In [464]:
bg_player_cols = pd.DataFrame()

In [436]:
test_bg.columns = test_bg.columns.get_level_values(1)

In [438]:
test_bg.head()

,Date,Day,Comp,Round,Venue,Result,Squad,Opponent,Start,Pos,...,GCA,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att,Succ,Match Report
0,2024-07-02,Tue,Copa América,Group stage,Neutral,D 1–1,br Brazil,co Colombia,Y,DM,...,1.0,44.0,48.0,91.7,6.0,42.0,1.0,2.0,2.0,Match Report
1,2024-07-06,Sat,Copa América,Quarter-finals,Neutral,D 0 (2)–0 (4),br Brazil,uy Uruguay,Y,DM,...,0.0,35.0,38.0,92.1,4.0,15.0,1.0,1.0,0.0,Match Report
2,2024-08-17,Sat,Premier League,Matchweek 1,Home,W 1–0,Newcastle Utd,Southampton,Y*,CM,...,0.0,18.0,28.0,64.3,1.0,17.0,0.0,0.0,0.0,Match Report
3,2024-08-25,Sun,Premier League,Matchweek 2,Away,D 1–1,Newcastle Utd,Bournemouth,Y*,CM,...,0.0,59.0,75.0,78.7,16.0,56.0,4.0,1.0,1.0,Match Report
4,2024-08-28,Wed,EFL Cup,Second round,Away,D 1 (4)–1 (3),Newcastle Utd,Nott'ham Forest,N,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Match Report

In [458]:
test_bg["Date"] = pd.to_datetime(test_bg["Date"], format="%Y-%m-%d")

In [466]:
bg_player_cols['Date'] = test_bg['Date'].copy()
bg_player_cols['Competition'] = test_bg['Comp'].copy()
bg_player_cols['Opponent'] = test_bg['Opponent'].copy()
bg_player_cols['Player'] = "Bruno Guimaraes"
bg_player_cols['Started the Game'] = test_bg['Start'].copy()
bg_player_cols['Position'] = test_bg['Pos'].copy()
bg_player_cols['Minutes'] = test_bg['Min'].copy()
bg_player_cols['Venue'] = test_bg['Venue'].copy()
bg_player_cols['Result'] = test_bg['Result'].copy()

In [468]:
bg_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-02,Copa América,co Colombia,Bruno Guimaraes,Y,DM,85.0,Neutral,D 1–1
1,2024-07-06,Copa América,uy Uruguay,Bruno Guimaraes,Y,DM,86.0,Neutral,D 0 (2)–0 (4)
2,2024-08-17,Premier League,Southampton,Bruno Guimaraes,Y*,CM,90.0,Home,W 1–0
3,2024-08-25,Premier League,Bournemouth,Bruno Guimaraes,Y*,CM,90.0,Away,D 1–1
4,2024-08-28,EFL Cup,Nott'ham Forest,Bruno Guimaraes,N,NaN,76.0,Away,D 1 (4)–1 (3)

In [470]:
bg_player_cols = bg_player_cols.dropna(subset=['Date'])

In [472]:
bg_player_cols.loc[bg_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0

In [474]:
bg_player_cols.sort_values(by=["Player","Date"])

bg_player_cols["7D Rolling Avg"] = bg_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
bg_player_cols["14D Rolling Avg"] = bg_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [476]:
bg_player_cols

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-02,Copa América,co Colombia,Bruno Guimaraes,Y,DM,85.0,Neutral,D 1–1,85.0,85.0
1,2024-07-06,Copa América,uy Uruguay,Bruno Guimaraes,Y,DM,86.0,Neutral,D 0 (2)–0 (4),171.0,171.0
2,2024-08-17,Premier League,Southampton,Bruno Guimaraes,Y*,CM,90.0,Home,W 1–0,90.0,90.0
3,2024-08-25,Premier League,Bournemouth,Bruno Guimaraes,Y*,CM,90.0,Away,D 1–1,90.0,180.0
4,2024-08-28,EFL Cup,Nott'ham Forest,Bruno Guimaraes,N,NaN,76.0,Away,D 1 (4)–1 (3),166.0,256.0
5,2024-09-01,Premier League,Tottenham,Bruno Guimaraes,Y*,CM,90.0,Home,W 2–1,166.0,256.0
6,2024-09-06,WCQ,ec Ecuador,Bruno Guimaraes,Y,DM,61.0,Home,W 1–0,151.0,317.0
7,2024-09-10,WCQ,py Paraguay,Bruno Guimaraes,Y,CM,45.0,Away,L 0–1,106.0,272.0
8,2024-09-15,Premier League,Wolves,Bruno Guimaraes,Y*,CM,86.0,Away,W 2–1,131.0,192.0
9,2024-09-21,Premier League,Fulham,Bruno Guimaraes,Y*,"DM,CM",90.0,Away,L 1–3,176.0,221.0
10,2024-09-28,Premier League,Manchester City,Bruno Guimaraes,Y*,CM,90.0,Home,D 1–1,90.0,266.0
11,2024-10-01,EFL Cup,AFC Wimbledon,Bruno Guimaraes,N,NaN,45.0,Home,W 1–0,135.0,225.0
12,2024-10-05,Premier League,Everton,Bruno Guimaraes,Y*,CM,90.0,Away,D 0–0,135.0,225.0
13,2024-10-10,WCQ,cl Chile,Bruno Guimaraes,N,NaN,45.0,Away,W 2–1,135.0,270.0
14,2024-10-15,WCQ,pe Peru,Bruno Guimaraes,Y,DM,78.0,Home,W 4–0,123.0,213.0
15,2024-10-19,Premier League,Brighton,Bruno Guimaraes,Y*,CM,84.0,Home,L 0–1,162.0,207.0
16,2024-10-27,Premier League,Chelsea,Bruno Guimaraes,Y*,CM,90.0,Away,L 1–2,90.0,252.0
17,2024-10-30,EFL Cup,Chelsea,Bruno Guimaraes,N,NaN,28.0,Home,W 2–0,118.0,202.0
18,2024-11-02,Premier League,Arsenal,Bruno Guimaraes,Y*,CM,89.0,Home,W 1–0,207.0,207.0
19,2024-11-10,Premier League,Nott'ham Forest,Bruno Guimaraes,Y*,CM,90.0,Away,W 3–1,90.0,207.0
20,2024-11-14,WCQ,ve Venezuela,Bruno Guimaraes,Y,DM,81.0,Away,D 1–1,171.0,260.0
21,2024-11-19,WCQ,uy Uruguay,Bruno Guimaraes,Y,CM,85.0,Home,D 1–1,166.0,256.0
22,2024-11-25,Premier League,West Ham,Bruno Guimaraes,Y*,"CM,DM",83.0,Home,L 0–2,168.0,249.0
23,2024-11-30,Premier League,Crystal Palace,Bruno Guimaraes,Y*,CM,90.0,Away,D 1–1,173.0,258.0
24,2024-12-04,Premier League,Liverpool,Bruno Guimaraes,Y*,CM,90.0,Home,D 3–3,180.0,263.0
25,2024-12-07,Premier League,Brentford,Bruno Guimaraes,Y*,CM,90.0,Away,L 2–4,180.0,353.0
26,2024-12-14,Premier League,Leicester City,Bruno Guimaraes,Y*,RM,64.0,Home,W 4–0,64.0,244.0
27,2024-12-18,EFL Cup,Brentford,Bruno Guimaraes,Y*,CM,90.0,Home,W 3–1,154.0,244.0
28,2024-12-21,Premier League,Ipswich Town,Bruno Guimaraes,Y*,CM,79.0,Away,W 4–0,169.0,233.0
29,2024-12-26,Premier League,Aston Villa,Bruno Guimaraes,Y*,RM,89.0,Home,W 3–0,168.0,322.0
30,2024-12-30,Premier League,Manchester Utd,Bruno Guimaraes,Y*,RM,90.0,Away,W 2–0,179.0,348.0
31,2025-01-04,Premier League,Tottenham,Bruno Guimaraes,Y*,RM,90.0,Away,W 2–1,180.0,269.0
33,2025-01-12,FA Cup,Bromley,Bruno Guimaraes,N,NaN,45.0,Home,W 3–1,135.0,225.0
34,2025-01-15,Premier League,Wolves,Bruno Guimaraes,Y*,RM,90.0,Home,W 3–0,224.0,224.0
35,2025-01-18,Premier League,Bournemouth,Bruno Guimaraes,Y*,RM,89.0,Home,L 1–4,79.0,303.0
36,2025-01-25,Premier League,Southampton,Bruno Guimaraes,Y*,RM,79.0,Away,W 3–1,86.0,165.0
37,2025-02-01,Premier League,Fulham,Bruno Guimaraes,Y*,RM,86.0,Home,L 1–2,175.0,254.0
38,2025-02-05,EFL Cup,Arsenal,Bruno Guimaraes,Y*,CM,89.0,Home,W 2–0,134.0,220.0
39,2025-02-08,FA Cup,Birmingham City,Bruno Guimaraes,Y*,CM,45.0,Away,W 3–2,71.0,205.0
40,2025-02-15,Premier League,Manchester City,Bruno Guimaraes,Y*,"RM,LM",71.0,Away,L 0–4,90.0,161.0
41,2025-02-23,Premier League,Nott'ham Forest,Bruno Guimaraes,Y*,"CM,LM",90.0,Home,W 4–3,177.0,248.0
42,2025-02-26,Premier League,Liverpool,Bruno Guimaraes,Y*,DM,87.0,Away,L 0–2,152.0,242.0
43,2025-03-02,FA Cup,Brighton,Bruno Guimaraes,N,NaN,65.0,Home,L 1–2,87.0,239.0
44,2025-03-10,Premier League,West Ham,Bruno Guimaraes,Y*,RM,87.0,Away,W 1–0,177.0,177.0
45,2025-03-16,EFL Cup,Liverpool,Bruno Guimaraes,Y*,CM,90.0,Neutral,W 2–1,167.0,254.0
46,2025-03-20,WCQ,co Colombia,Bruno Guimaraes,Y,CM,77.0,Home,W 2–1,90.0,167.0
47,2025-04-02,Premier League,Brentford,Bruno Guimaraes,Y*,RM,90.0,Home,W 2–1,154.0,154.0
48,2025-04-07,Premier League,Leicester City,Bruno Guimaraes,Y*,RM,64.0,Away,W 3–0,148.0,238.0
49,2025-04-13,Premier League,Manchester Utd,Bruno Guimaraes,Y*,RM,84.0,Home,W 4–1,155.0,219.0
50,2025-04-16,Premier League,Crystal Palace,Bruno Guimaraes,Y*,RM,71.0,Home,W 5–0,245.0,309.0
51,2025-04-19,Premier League,Aston Villa,Bruno Guimaraes,Y*,RM,90.0,Away,L 1–4,90.0,335.0
52,2025-04-26,Premier League,Ipswich Town,Bruno Guimaraes,Y*,"RM,LM",90.0,Home,W 3–0,90.0,180.0
53,2025-05-04,Premier League,Brighton,Bruno Guimaraes,Y*,"RM,DM",90.0,Away,D 1–1,89.0,179.0
54,2025-05-11,Premier League,Chelsea,Bruno Guimaraes,Y*,"CM,LM",89.0,Home,W 2–0,90.0,179.0
55,2025-05-18,Premier League,Arsenal,Bruno Guimaraes,Y*,"CM,AM",90.0,Away,L 0–1,90.0,180.0
56,2025-05-25,Premier League,Everton,Bruno Guimaraes,Y*,"RM,CM",90.0,Home,L 0–1,89.0,179.0
57,2025-06-05,WCQ,ec Ecuador,Bruno Guimaraes,Y,CM,89.0,Away,D 0–0,179.0,179.0
58,2025-06-10,WCQ,py Paraguay,Bruno Guimaraes,Y,DM,90.0,Home,W 1–0,NaN,NaN

In [282]:
test_rg = pd.read_html('https://fbref.com/en/players/b8e740fb/matchlogs/2024-2025/Ryan-Gravenberch-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [284]:
test_rg.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Date                Day               Comp              Round
0         2024-07-02                Tue          UEFA Euro        Round of 16
1         2024-07-06                Sat          UEFA Euro     Quarter-finals
2         2024-07-10                Wed          UEFA Euro        Semi-finals
3         2024-08-17                Sat     Premier League        Matchweek 1
4         2024-08-25                Sun     Premier League        Matchweek 2

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Venue             Result              Squad           Opponent
0            Neutral              W 3–0     nl Netherlands         ro Romania
1            Neutral              W 2–1     nl Netherlands         tr Türkiye
2            Neutral              L 1–2     nl Netherlands        eng England
3               Away              W 2–0          Liverpool       Ipswich Town
4               Home              W 2–0          Liverpool          Brentford

  Unnamed: 8_level_0                   Unnamed: 9_level_0  ...  \
               Start                                  Pos  ...
0                  N  On matchday squad, but did not play  ...
1                  N  On matchday squad, but did not play  ...
2                  N  On matchday squad, but did not play  ...
3                  Y                                   DM  ...
4                  Y                                   DM  ...

                                   SCA                               Passes  \
                                   GCA                                  Cmp
0  On matchday squad, but did not play  On matchday squad, but did not play
1  On matchday squad, but did not play  On matchday squad, but did not play
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                    1                                   51
4                                    0                                   71

                                                                             \
                                   Att                                 Cmp%
0  On matchday squad, but did not play  On matchday squad, but did not play
1  On matchday squad, but did not play  On matchday squad, but did not play
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                   59                                 86.4
4                                   76                                 93.4

                                                                    Carries  \
                                  PrgP                              Carries
0  On matchday squad, but did not play  On matchday squad, but did not play
1  On matchday squad, but did not play  On matchday squad, but did not play
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                    5                                   40
4                                    6                                   60

                                                                   Take-Ons  \
                                  PrgC                                  Att
0  On matchday squad, but did not play  On matchday squad, but did not play
1  On matchday squad, but did not play  On matchday squad, but did not play
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                    2                                    2
4                                    1                                    2

                                       Unnamed: 36_level_0
                                  Succ        Match Report
0  On matchday squad, but did not play        Match Report
1  On matchday squad, but did not play        Match Report
2  On matchday squad, but did not play        Match Report
3                                    1        Match Report
4                                    1        Match Report

[5 rows x 37 columns]

In [286]:
rg_player_cols = pd.DataFrame()

In [288]:
rg_player_cols['Date'] = test_rg['Unnamed: 0_level_0']['Date'].copy()
rg_player_cols['Competition'] = test_rg['Unnamed: 2_level_0']['Comp'].copy()
rg_player_cols['Opponent'] = test_rg['Unnamed: 7_level_0']['Opponent'].copy()
rg_player_cols['Player'] = "Ryan Gravenberch"
rg_player_cols['Started the Game'] = test_rg['Unnamed: 8_level_0']['Start'].copy()
rg_player_cols['Position'] = test_rg['Unnamed: 9_level_0']['Pos'].copy()
rg_player_cols['Minutes'] = test_rg['Unnamed: 10_level_0']['Min'].copy()
rg_player_cols['Venue'] = test_rg['Unnamed: 4_level_0']['Venue'].copy()
rg_player_cols['Venue'] = test_rg['Unnamed: 4_level_0']['Venue'].copy()
rg_player_cols['Result'] = test_rg['Unnamed: 5_level_0']['Result'].copy()

In [290]:
rg_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-02,UEFA Euro,ro Romania,Ryan Gravenberch,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,W 3–0
1,2024-07-06,UEFA Euro,tr Türkiye,Ryan Gravenberch,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,W 2–1
2,2024-07-10,UEFA Euro,eng England,Ryan Gravenberch,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,L 1–2
3,2024-08-17,Premier League,Ipswich Town,Ryan Gravenberch,Y,DM,90,Away,W 2–0
4,2024-08-25,Premier League,Brentford,Ryan Gravenberch,Y,DM,89,Home,W 2–0

In [292]:
rg_player_cols= rg_player_cols.dropna(subset=['Date'])

In [294]:
rg_player_cols.loc[rg_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
rg_player_cols["Date"] = pd.to_datetime(rg_player_cols["Date"], format="%Y-%m-%d")

rg_player_cols.sort_values(by=["Player","Date"])

rg_player_cols["7D Rolling Avg"] = rg_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
rg_player_cols["14D Rolling Avg"] = rg_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [296]:
rg_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-02,UEFA Euro,ro Romania,Ryan Gravenberch,N,"On matchday squad, but did not play",0,Neutral,W 3–0,0.0,0.0
1,2024-07-06,UEFA Euro,tr Türkiye,Ryan Gravenberch,N,"On matchday squad, but did not play",0,Neutral,W 2–1,0.0,0.0
2,2024-07-10,UEFA Euro,eng England,Ryan Gravenberch,N,"On matchday squad, but did not play",0,Neutral,L 1–2,0.0,0.0
3,2024-08-17,Premier League,Ipswich Town,Ryan Gravenberch,Y,DM,90,Away,W 2–0,90.0,90.0
4,2024-08-25,Premier League,Brentford,Ryan Gravenberch,Y,DM,89,Home,W 2–0,89.0,179.0

In [266]:
test_yt = pd.read_html('https://fbref.com/en/players/56f7a928/matchlogs/2024-2025/Youri-Tielemans-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [268]:
test_yt.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-07-01                Mon            UEFA Euro
1         2024-08-17                Sat       Premier League
2         2024-08-24                Sat       Premier League
3         2024-08-31                Sat       Premier League
4         2024-09-06                Fri  UEFA Nations League

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Round              Venue             Result              Squad
0        Round of 16            Neutral              L 0–1         be Belgium
1        Matchweek 1               Away              W 2–1        Aston Villa
2        Matchweek 2               Home              L 0–2        Aston Villa
3        Matchweek 3               Away              W 2–1        Aston Villa
4           League A               Home              W 3–1         be Belgium

  Unnamed: 7_level_0 Unnamed: 8_level_0                   Unnamed: 9_level_0  \
            Opponent              Start                                  Pos
0          fr France                  N  On matchday squad, but did not play
1           West Ham                  Y                                   DM
2            Arsenal                  Y                                   CM
3     Leicester City                  Y                                   CM
4          il Israel                  Y                                   DM

   ...                                  SCA  \
   ...                                  GCA
0  ...  On matchday squad, but did not play
1  ...                                    1
2  ...                                    0
3  ...                                    0
4  ...                                  NaN

                                Passes                                       \
                                   Cmp                                  Att
0  On matchday squad, but did not play  On matchday squad, but did not play
1                                   47                                   53
2                                   28                                   33
3                                   52                                   63
4                                  NaN                                  NaN

                                                                             \
                                  Cmp%                                 PrgP
0  On matchday squad, but did not play  On matchday squad, but did not play
1                                 88.7                                    4
2                                 84.8                                    3
3                                 82.5                                    4
4                                  NaN                                  NaN

                               Carries                                       \
                               Carries                                 PrgC
0  On matchday squad, but did not play  On matchday squad, but did not play
1                                   43                                    2
2                                   20                                    0
3                                   32                                    2
4                                  NaN                                  NaN

                              Take-Ons                                       \
                                   Att                                 Succ
0  On matchday squad, but did not play  On matchday squad, but did not play
1                                    2                                    1
2                                    3                                    1
3                                    2                                    2
4                                  NaN                                  NaN

  Unnamed: 36_level_0
         Match Report
0        Match Report
1        Match Report
2        Match Report
3        Match Report
4        Match Report

[5 rows x 37 columns]

In [270]:
yt_player_cols = pd.DataFrame()

In [272]:
yt_player_cols['Date'] = test_yt['Unnamed: 0_level_0']['Date'].copy()
yt_player_cols['Competition'] = test_yt['Unnamed: 2_level_0']['Comp'].copy()
yt_player_cols['Opponent'] = test_yt['Unnamed: 7_level_0']['Opponent'].copy()
yt_player_cols['Player'] = "Youri Tielemans"
yt_player_cols['Started the Game'] = test_yt['Unnamed: 8_level_0']['Start'].copy()
yt_player_cols['Position'] = test_yt['Unnamed: 9_level_0']['Pos'].copy()
yt_player_cols['Minutes'] = test_yt['Unnamed: 10_level_0']['Min'].copy()
yt_player_cols['Venue'] = test_yt['Unnamed: 4_level_0']['Venue'].copy()
yt_player_cols['Venue'] = test_yt['Unnamed: 4_level_0']['Venue'].copy()
yt_player_cols['Result'] = test_yt['Unnamed: 5_level_0']['Result'].copy()

In [274]:
yt_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-01,UEFA Euro,fr France,Youri Tielemans,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,L 0–1
1,2024-08-17,Premier League,West Ham,Youri Tielemans,Y,DM,90,Away,W 2–1
2,2024-08-24,Premier League,Arsenal,Youri Tielemans,Y,CM,90,Home,L 0–2
3,2024-08-31,Premier League,Leicester City,Youri Tielemans,Y,CM,90,Away,W 2–1
4,2024-09-06,UEFA Nations League,il Israel,Youri Tielemans,Y,DM,73,Home,W 3–1

In [276]:
yt_player_cols= yt_player_cols.dropna(subset=['Date'])

In [278]:
yt_player_cols.loc[yt_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
yt_player_cols["Date"] = pd.to_datetime(yt_player_cols["Date"], format="%Y-%m-%d")

yt_player_cols.sort_values(by=["Player","Date"])

yt_player_cols["7D Rolling Avg"] = yt_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
yt_player_cols["14D Rolling Avg"] = yt_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [280]:
yt_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01,UEFA Euro,fr France,Youri Tielemans,N,"On matchday squad, but did not play",0,Neutral,L 0–1,0.0,0.0
1,2024-08-17,Premier League,West Ham,Youri Tielemans,Y,DM,90,Away,W 2–1,90.0,90.0
2,2024-08-24,Premier League,Arsenal,Youri Tielemans,Y,CM,90,Home,L 0–2,90.0,180.0
3,2024-08-31,Premier League,Leicester City,Youri Tielemans,Y,CM,90,Away,W 2–1,90.0,180.0
4,2024-09-06,UEFA Nations League,il Israel,Youri Tielemans,Y,DM,73,Home,W 3–1,163.0,253.0

In [250]:
test_bf = pd.read_html('https://fbref.com/en/players/507c7bdf/matchlogs/2024-2025/Bruno-Fernandes-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [252]:
test_bf.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-07-01                Mon            UEFA Euro
1         2024-07-05                Fri            UEFA Euro
2         2024-08-10                Sat  FA Community Shield
3         2024-08-16                Fri       Premier League
4         2024-08-24                Sat       Premier League

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                 Round              Venue             Result
0          Round of 16            Neutral      D 0 (3)–0 (0)
1       Quarter-finals            Neutral      D 0 (3)–0 (5)
2  FA Community Shield               Away      D 1 (6)–1 (7)
3          Matchweek 1               Home              W 1–0
4          Matchweek 2               Away              L 1–2

  Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  \
               Squad           Opponent              Start                Pos
0        pt Portugal        si Slovenia                  Y              AM,DM
1        pt Portugal          fr France                  Y                 AM
2     Manchester Utd    Manchester City                 Y*                 FW
3     Manchester Utd             Fulham                 Y*              FW,AM
4     Manchester Utd           Brighton                 Y*              FW,AM

   ...  SCA Passes                 Carries      Take-Ons       \
   ...  GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0  ...    0     70  101  69.3   17      77    5        1    0
1  ...    0     44   59  74.6    5      37    0        2    0
2  ...  NaN    NaN  NaN   NaN  NaN     NaN  NaN      NaN  NaN
3  ...    0     43   60  71.7    6      50    7        1    1
4  ...    0     32   45  71.1    6      30    1        0    0

  Unnamed: 36_level_0
         Match Report
0        Match Report
1        Match Report
2        Match Report
3        Match Report
4        Match Report

[5 rows x 37 columns]

In [254]:
bf_player_cols = pd.DataFrame()

In [256]:
bf_player_cols['Date'] = test_bf['Unnamed: 0_level_0']['Date'].copy()
bf_player_cols['Competition'] = test_bf['Unnamed: 2_level_0']['Comp'].copy()
bf_player_cols['Opponent'] = test_bf['Unnamed: 7_level_0']['Opponent'].copy()
bf_player_cols['Player'] = "Bruno Fernandes"
bf_player_cols['Started the Game'] = test_bf['Unnamed: 8_level_0']['Start'].copy()
bf_player_cols['Position'] = test_bf['Unnamed: 9_level_0']['Pos'].copy()
bf_player_cols['Minutes'] = test_bf['Unnamed: 10_level_0']['Min'].copy()
bf_player_cols['Venue'] = test_bf['Unnamed: 4_level_0']['Venue'].copy()
bf_player_cols['Venue'] = test_bf['Unnamed: 4_level_0']['Venue'].copy()
bf_player_cols['Result'] = test_bf['Unnamed: 5_level_0']['Result'].copy()

In [258]:
bf_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-01,UEFA Euro,si Slovenia,Bruno Fernandes,Y,"AM,DM",120,Neutral,D 0 (3)–0 (0)
1,2024-07-05,UEFA Euro,fr France,Bruno Fernandes,Y,AM,74,Neutral,D 0 (3)–0 (5)
2,2024-08-10,FA Community Shield,Manchester City,Bruno Fernandes,Y*,FW,90,Away,D 1 (6)–1 (7)
3,2024-08-16,Premier League,Fulham,Bruno Fernandes,Y*,"FW,AM",90,Home,W 1–0
4,2024-08-24,Premier League,Brighton,Bruno Fernandes,Y*,"FW,AM",78,Away,L 1–2

In [260]:
bf_player_cols= bf_player_cols.dropna(subset=['Date'])

In [262]:
bf_player_cols.loc[bf_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
bf_player_cols["Date"] = pd.to_datetime(bf_player_cols["Date"], format="%Y-%m-%d")

bf_player_cols.sort_values(by=["Player","Date"])

bf_player_cols["7D Rolling Avg"] = bf_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
bf_player_cols["14D Rolling Avg"] = bf_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [264]:
bf_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01,UEFA Euro,si Slovenia,Bruno Fernandes,Y,"AM,DM",120,Neutral,D 0 (3)–0 (0),120.0,120.0
1,2024-07-05,UEFA Euro,fr France,Bruno Fernandes,Y,AM,74,Neutral,D 0 (3)–0 (5),194.0,194.0
2,2024-08-10,FA Community Shield,Manchester City,Bruno Fernandes,Y*,FW,90,Away,D 1 (6)–1 (7),90.0,90.0
3,2024-08-16,Premier League,Fulham,Bruno Fernandes,Y*,"FW,AM",90,Home,W 1–0,180.0,180.0
4,2024-08-24,Premier League,Brighton,Bruno Fernandes,Y*,"FW,AM",78,Away,L 1–2,78.0,168.0

In [234]:
test_mr = pd.read_html('https://fbref.com/en/players/2e5915f1/matchlogs/2024-2025/Morgan-Rogers-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [236]:
test_mr.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Date                Day               Comp              Round
0         2024-08-17                Sat     Premier League        Matchweek 1
1         2024-08-24                Sat     Premier League        Matchweek 2
2         2024-08-31                Sat     Premier League        Matchweek 3
3         2024-09-14                Sat     Premier League        Matchweek 4
4         2024-09-17                Tue       Champions Lg       League phase

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Venue             Result              Squad           Opponent
0               Away              W 2–1        Aston Villa           West Ham
1               Home              L 0–2        Aston Villa            Arsenal
2               Away              W 2–1        Aston Villa     Leicester City
3               Home              W 3–2        Aston Villa            Everton
4               Away              W 3–0    eng Aston Villa      ch Young Boys

  Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes                   \
               Start                Pos  ...  GCA    Cmp   Att  Cmp% PrgP
0                  Y                 AM  ...  0.0   19.0  24.0  79.2  3.0
1                  Y                 FW  ...  0.0   20.0  30.0  66.7  0.0
2                  Y                 FW  ...  0.0   13.0  17.0  76.5  1.0
3                  Y           AM,LM,LW  ...  0.0   20.0  27.0  74.1  5.0
4                  Y                 AM  ...  0.0   22.0  33.0  66.7  6.0

  Carries      Take-Ons      Unnamed: 36_level_0
  Carries PrgC      Att Succ        Match Report
0    13.0  4.0      2.0  1.0        Match Report
1    26.0  7.0      7.0  5.0        Match Report
2    17.0  0.0      6.0  1.0        Match Report
3    26.0  3.0      6.0  2.0        Match Report
4    32.0  5.0      5.0  4.0        Match Report

[5 rows x 37 columns]

In [238]:
mr_player_cols = pd.DataFrame()

In [240]:
mr_player_cols['Date'] = test_mr['Unnamed: 0_level_0']['Date'].copy()
mr_player_cols['Competition'] = test_mr['Unnamed: 2_level_0']['Comp'].copy()
mr_player_cols['Opponent'] = test_mr['Unnamed: 7_level_0']['Opponent'].copy()
mr_player_cols['Player'] = "Morgan Rogers"
mr_player_cols['Started the Game'] = test_mr['Unnamed: 8_level_0']['Start'].copy()
mr_player_cols['Position'] = test_mr['Unnamed: 9_level_0']['Pos'].copy()
mr_player_cols['Minutes'] = test_mr['Unnamed: 10_level_0']['Min'].copy()
mr_player_cols['Venue'] = test_mr['Unnamed: 4_level_0']['Venue'].copy()
mr_player_cols['Venue'] = test_mr['Unnamed: 4_level_0']['Venue'].copy()
mr_player_cols['Result'] = test_mr['Unnamed: 5_level_0']['Result'].copy()

In [242]:
mr_player_cols= mr_player_cols.dropna(subset=['Date'])

In [244]:
mr_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-08-17,Premier League,West Ham,Morgan Rogers,Y,AM,90.0,Away,W 2–1
1,2024-08-24,Premier League,Arsenal,Morgan Rogers,Y,FW,90.0,Home,L 0–2
2,2024-08-31,Premier League,Leicester City,Morgan Rogers,Y,FW,90.0,Away,W 2–1
3,2024-09-14,Premier League,Everton,Morgan Rogers,Y,"AM,LM,LW",90.0,Home,W 3–2
4,2024-09-17,Champions Lg,ch Young Boys,Morgan Rogers,Y,AM,87.0,Away,W 3–0

In [246]:
mr_player_cols.loc[mr_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
mr_player_cols["Date"] = pd.to_datetime(mr_player_cols["Date"], format="%Y-%m-%d")

mr_player_cols.sort_values(by=["Player","Date"])

mr_player_cols["7D Rolling Avg"] = mr_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
mr_player_cols["14D Rolling Avg"] = mr_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [248]:
mr_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-17,Premier League,West Ham,Morgan Rogers,Y,AM,90.0,Away,W 2–1,90.0,90.0
1,2024-08-24,Premier League,Arsenal,Morgan Rogers,Y,FW,90.0,Home,L 0–2,90.0,180.0
2,2024-08-31,Premier League,Leicester City,Morgan Rogers,Y,FW,90.0,Away,W 2–1,90.0,180.0
3,2024-09-14,Premier League,Everton,Morgan Rogers,Y,"AM,LM,LW",90.0,Home,W 3–2,90.0,90.0
4,2024-09-17,Champions Lg,ch Young Boys,Morgan Rogers,Y,AM,87.0,Away,W 3–0,177.0,177.0

In [218]:
test_bm = pd.read_html('https://fbref.com/en/players/6afaebf2/matchlogs/2024-2025/Bryan-Mbeumo-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [220]:
test_bm.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0                   Unnamed: 2_level_0  \
                Date                Day                                 Comp
0         2024-08-18                Sun                       Premier League
1         2024-08-25                Sun                       Premier League
2                NaN                NaN                                  NaN
3         2024-08-31                Sat                       Premier League
4         2024-09-07                Sat  Africa Cup of Nations qualification

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Round              Venue             Result              Squad
0        Matchweek 1               Home              W 2–1          Brentford
1        Matchweek 2               Away              L 0–2          Brentford
2                NaN                NaN                NaN                NaN
3        Matchweek 3               Home              W 3–1          Brentford
4        Group stage               Home              W 1–0        cm Cameroon

  Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes  \
            Opponent              Start                Pos  ...  GCA    Cmp
0     Crystal Palace                  Y              RW,FW  ...  0.0   16.0
1          Liverpool                  Y                 FW  ...  0.0   16.0
2                NaN                NaN                NaN  ...  NaN    NaN
3        Southampton                  Y              RW,LW  ...  1.0   29.0
4         na Namibia                  Y                 RW  ...  NaN    NaN

                   Carries      Take-Ons      Unnamed: 36_level_0
    Att  Cmp% PrgP Carries PrgC      Att Succ        Match Report
0  32.0  50.0  1.0    23.0  3.0      1.0  1.0        Match Report
1  20.0  80.0  2.0    16.0  4.0      4.0  1.0        Match Report
2   NaN   NaN  NaN     NaN  NaN      NaN  NaN                 NaN
3  37.0  78.4  5.0    28.0  4.0      1.0  1.0        Match Report
4   NaN   NaN  NaN     NaN  NaN      NaN  NaN        Match Report

[5 rows x 37 columns]

In [222]:
bm_player_cols = pd.DataFrame()

In [224]:
bm_player_cols['Date'] = test_bm['Unnamed: 0_level_0']['Date'].copy()
bm_player_cols['Competition'] = test_bm['Unnamed: 2_level_0']['Comp'].copy()
bm_player_cols['Opponent'] = test_bm['Unnamed: 7_level_0']['Opponent'].copy()
bm_player_cols['Player'] = "Bryan Mbeumo"
bm_player_cols['Started the Game'] = test_bm['Unnamed: 8_level_0']['Start'].copy()
bm_player_cols['Position'] = test_bm['Unnamed: 9_level_0']['Pos'].copy()
bm_player_cols['Minutes'] = test_bm['Unnamed: 10_level_0']['Min'].copy()
bm_player_cols['Venue'] = test_bm['Unnamed: 4_level_0']['Venue'].copy()
bm_player_cols['Venue'] = test_bm['Unnamed: 4_level_0']['Venue'].copy()
bm_player_cols['Result'] = test_bm['Unnamed: 5_level_0']['Result'].copy()

In [226]:
bm_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-08-18,Premier League,Crystal Palace,Bryan Mbeumo,Y,"RW,FW",89.0,Home,W 2–1
1,2024-08-25,Premier League,Liverpool,Bryan Mbeumo,Y,FW,90.0,Away,L 0–2
2,NaN,NaN,NaN,Bryan Mbeumo,NaN,NaN,NaN,NaN,NaN
3,2024-08-31,Premier League,Southampton,Bryan Mbeumo,Y,"RW,LW",90.0,Home,W 3–1
4,2024-09-07,Africa Cup of Nations qualification,na Namibia,Bryan Mbeumo,Y,RW,90.0,Home,W 1–0

In [228]:
bm_player_cols= bm_player_cols.dropna(subset=['Date'])

In [230]:
bm_player_cols.loc[bm_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
bm_player_cols["Date"] = pd.to_datetime(bm_player_cols["Date"], format="%Y-%m-%d")

bm_player_cols.sort_values(by=["Player","Date"])

bm_player_cols["7D Rolling Avg"] = bm_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
bm_player_cols["14D Rolling Avg"] = bm_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [232]:
bm_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-18,Premier League,Crystal Palace,Bryan Mbeumo,Y,"RW,FW",89.0,Home,W 2–1,89.0,89.0
1,2024-08-25,Premier League,Liverpool,Bryan Mbeumo,Y,FW,90.0,Away,L 0–2,90.0,179.0
3,2024-08-31,Premier League,Southampton,Bryan Mbeumo,Y,"RW,LW",90.0,Home,W 3–1,90.0,270.0
4,2024-09-07,Africa Cup of Nations qualification,na Namibia,Bryan Mbeumo,Y,RW,90.0,Home,W 1–0,180.0,270.0
5,2024-09-10,Africa Cup of Nations qualification,zw Zimbabwe,Bryan Mbeumo,Y,AM,90.0,Away,D 0–0,180.0,270.0

In [202]:
test_ms = pd.read_html('https://fbref.com/en/players/e342ad68/matchlogs/2024-2025/Mohamed-Salah-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [204]:
test_ms.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0                   Unnamed: 2_level_0  \
                Date                Day                                 Comp
0         2024-08-17                Sat                       Premier League
1         2024-08-25                Sun                       Premier League
2         2024-09-01                Sun                       Premier League
3         2024-09-06                Fri  Africa Cup of Nations qualification
4         2024-09-10                Tue  Africa Cup of Nations qualification

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Round              Venue             Result              Squad
0        Matchweek 1               Away              W 2–0          Liverpool
1        Matchweek 2               Home              W 2–0          Liverpool
2        Matchweek 3               Away              W 3–0          Liverpool
3        Group stage               Home              W 3–0           eg Egypt
4        Group stage               Away              W 4–0           eg Egypt

  Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes  \
            Opponent              Start                Pos  ...  GCA    Cmp
0       Ipswich Town                  Y                 RW  ...  1.0   25.0
1          Brentford                  Y                 RW  ...  0.0   30.0
2     Manchester Utd                  Y                 RW  ...  2.0   27.0
3      cv Cape Verde                 Y*                 AM  ...  NaN    NaN
4        bw Botswana                 Y*                 AM  ...  NaN    NaN

                    Carries      Take-Ons      Unnamed: 36_level_0
    Att  Cmp%  PrgP Carries PrgC      Att Succ        Match Report
0  34.0  73.5   1.0    26.0  2.0      2.0  0.0        Match Report
1  35.0  85.7  10.0    40.0  6.0      2.0  2.0        Match Report
2  35.0  77.1   2.0    32.0  5.0      4.0  2.0        Match Report
3   NaN   NaN   NaN     NaN  NaN      NaN  NaN        Match Report
4   NaN   NaN   NaN     NaN  NaN      NaN  NaN        Match Report

[5 rows x 37 columns]

In [206]:
ms_player_cols = pd.DataFrame()

In [208]:
ms_player_cols['Date'] = test_ms['Unnamed: 0_level_0']['Date'].copy()
ms_player_cols['Competition'] = test_ms['Unnamed: 2_level_0']['Comp'].copy()
ms_player_cols['Opponent'] = test_ms['Unnamed: 7_level_0']['Opponent'].copy()
ms_player_cols['Player'] = "Mohamed Salah"
ms_player_cols['Started the Game'] = test_ms['Unnamed: 8_level_0']['Start'].copy()
ms_player_cols['Position'] = test_ms['Unnamed: 9_level_0']['Pos'].copy()
ms_player_cols['Minutes'] = test_ms['Unnamed: 10_level_0']['Min'].copy()
ms_player_cols['Venue'] = test_ms['Unnamed: 4_level_0']['Venue'].copy()
ms_player_cols['Venue'] = test_ms['Unnamed: 4_level_0']['Venue'].copy()
ms_player_cols['Result'] = test_ms['Unnamed: 5_level_0']['Result'].copy()

In [210]:
ms_player_cols= ms_player_cols.dropna(subset=['Date'])

In [212]:
ms_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-08-17,Premier League,Ipswich Town,Mohamed Salah,Y,RW,90.0,Away,W 2–0
1,2024-08-25,Premier League,Brentford,Mohamed Salah,Y,RW,82.0,Home,W 2–0
2,2024-09-01,Premier League,Manchester Utd,Mohamed Salah,Y,RW,90.0,Away,W 3–0
3,2024-09-06,Africa Cup of Nations qualification,cv Cape Verde,Mohamed Salah,Y*,AM,90.0,Home,W 3–0
4,2024-09-10,Africa Cup of Nations qualification,bw Botswana,Mohamed Salah,Y*,AM,74.0,Away,W 4–0

In [214]:
ms_player_cols.loc[ms_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
ms_player_cols["Date"] = pd.to_datetime(ms_player_cols["Date"], format="%Y-%m-%d")

ms_player_cols.sort_values(by=["Player","Date"])

ms_player_cols["7D Rolling Avg"] = ms_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
ms_player_cols["14D Rolling Avg"] = ms_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [216]:
ms_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-17,Premier League,Ipswich Town,Mohamed Salah,Y,RW,90.0,Away,W 2–0,90.0,90.0
1,2024-08-25,Premier League,Brentford,Mohamed Salah,Y,RW,82.0,Home,W 2–0,82.0,172.0
2,2024-09-01,Premier League,Manchester Utd,Mohamed Salah,Y,RW,90.0,Away,W 3–0,90.0,172.0
3,2024-09-06,Africa Cup of Nations qualification,cv Cape Verde,Mohamed Salah,Y*,AM,90.0,Home,W 3–0,180.0,262.0
4,2024-09-10,Africa Cup of Nations qualification,bw Botswana,Mohamed Salah,Y*,AM,74.0,Away,W 4–0,164.0,254.0

In [170]:
test_ai = pd.read_html('https://fbref.com/en/players/8e92be30/matchlogs/2024-2025/Alexander-Isak-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [172]:
test_ai.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-08-17                Sat       Premier League
1         2024-08-25                Sun       Premier League
2         2024-08-28                Wed              EFL Cup
3         2024-09-01                Sun       Premier League
4         2024-09-05                Thu  UEFA Nations League

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Round              Venue             Result              Squad
0        Matchweek 1               Home              W 1–0      Newcastle Utd
1        Matchweek 2               Away              D 1–1      Newcastle Utd
2       Second round               Away      D 1 (4)–1 (3)      Newcastle Utd
3        Matchweek 3               Home              W 2–1      Newcastle Utd
4           League C               Away              W 3–1          se Sweden

  Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes  \
            Opponent              Start                Pos  ...  GCA    Cmp
0        Southampton                  Y                 FW  ...  2.0    8.0
1        Bournemouth                  Y                 FW  ...  0.0   11.0
2    Nott'ham Forest                  Y                 FW  ...  NaN    NaN
3          Tottenham                  Y                 FW  ...  0.0    9.0
4      az Azerbaijan                  Y                 FW  ...  NaN    NaN

                   Carries      Take-Ons      Unnamed: 36_level_0
    Att  Cmp% PrgP Carries PrgC      Att Succ        Match Report
0  10.0  80.0  1.0     6.0  0.0      1.0  0.0        Match Report
1  19.0  57.9  1.0    27.0  5.0      4.0  1.0        Match Report
2   NaN   NaN  NaN     NaN  NaN      NaN  NaN        Match Report
3  12.0  75.0  0.0    14.0  2.0      3.0  1.0        Match Report
4   NaN   NaN  NaN     NaN  NaN      NaN  NaN        Match Report

[5 rows x 37 columns]

In [174]:
ai_player_cols = pd.DataFrame()

In [176]:
ai_player_cols['Date'] = test_ai['Unnamed: 0_level_0']['Date'].copy()
ai_player_cols['Competition'] = test_ai['Unnamed: 2_level_0']['Comp'].copy()
ai_player_cols['Opponent'] = test_ai['Unnamed: 7_level_0']['Opponent'].copy()
ai_player_cols['Player'] = "Alexander Isak"
ai_player_cols['Started the Game'] = test_ai['Unnamed: 8_level_0']['Start'].copy()
ai_player_cols['Position'] = test_ai['Unnamed: 9_level_0']['Pos'].copy()
ai_player_cols['Minutes'] = test_ai['Unnamed: 10_level_0']['Min'].copy()
ai_player_cols['Venue'] = test_ai['Unnamed: 4_level_0']['Venue'].copy()
ai_player_cols['Venue'] = test_ai['Unnamed: 4_level_0']['Venue'].copy()
ai_player_cols['Result'] = test_ai['Unnamed: 5_level_0']['Result'].copy()

In [178]:
ai_player_cols= ai_player_cols.dropna(subset=['Date'])

In [514]:
ai_player_cols

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-17,Premier League,Southampton,Alexander Isak,Y,FW,90.0,Home,W 1–0,90.0,90.0
1,2024-08-25,Premier League,Bournemouth,Alexander Isak,Y,FW,90.0,Away,D 1–1,90.0,180.0
2,2024-08-28,EFL Cup,Nott'ham Forest,Alexander Isak,Y,FW,90.0,Away,D 1 (4)–1 (3),180.0,270.0
3,2024-09-01,Premier League,Tottenham,Alexander Isak,Y,FW,90.0,Home,W 2–1,180.0,270.0
4,2024-09-05,UEFA Nations League,az Azerbaijan,Alexander Isak,Y,FW,90.0,Away,W 3–1,180.0,360.0
5,2024-09-08,UEFA Nations League,ee Estonia,Alexander Isak,Y,FW,78.0,Home,W 3–0,168.0,348.0
6,2024-09-15,Premier League,Wolves,Alexander Isak,Y,FW,45.0,Away,W 2–1,45.0,213.0
7,2024-09-21,Premier League,Fulham,Alexander Isak,Y,"FW,AM",90.0,Away,L 1–3,135.0,213.0
9,2024-10-19,Premier League,Brighton,Alexander Isak,Y,FW,90.0,Home,L 0–1,90.0,180.0
10,2024-10-27,Premier League,Chelsea,Alexander Isak,Y,FW,90.0,Away,L 1–2,152.0,242.0
11,2024-10-30,EFL Cup,Chelsea,Alexander Isak,Y,FW,62.0,Home,W 2–0,242.0,242.0
12,2024-11-02,Premier League,Arsenal,Alexander Isak,Y,FW,90.0,Home,W 1–0,89.0,241.0
13,2024-11-10,Premier League,Nott'ham Forest,Alexander Isak,Y,FW,89.0,Away,W 3–1,179.0,179.0
14,2024-11-16,UEFA Nations League,sk Slovakia,Alexander Isak,Y,FW,90.0,Home,W 2–1,180.0,269.0
15,2024-11-19,UEFA Nations League,az Azerbaijan,Alexander Isak,Y,FW,90.0,Home,W 6–0,180.0,270.0
16,2024-11-25,Premier League,West Ham,Alexander Isak,Y,FW,90.0,Home,L 0–2,111.0,201.0
17,2024-11-30,Premier League,Crystal Palace,Alexander Isak,Y,FW,21.0,Away,D 1–1,111.0,201.0
18,2024-12-04,Premier League,Liverpool,Alexander Isak,Y,"FW,LW",90.0,Home,D 3–3,180.0,291.0
19,2024-12-07,Premier League,Brentford,Alexander Isak,Y,FW,90.0,Away,L 2–4,72.0,252.0
20,2024-12-14,Premier League,Leicester City,Alexander Isak,Y,FW,72.0,Home,W 4–0,148.0,238.0
21,2024-12-18,EFL Cup,Brentford,Alexander Isak,Y,FW,76.0,Home,W 3–1,148.0,220.0
22,2024-12-21,Premier League,Ipswich Town,Alexander Isak,Y,FW,72.0,Away,W 4–0,161.0,309.0
23,2024-12-26,Premier League,Aston Villa,Alexander Isak,Y,FW,89.0,Home,W 3–0,179.0,327.0
24,2024-12-30,Premier League,Manchester Utd,Alexander Isak,Y,FW,90.0,Away,W 2–0,175.0,264.0
25,2025-01-04,Premier League,Tottenham,Alexander Isak,Y,FW,85.0,Away,W 2–1,149.0,328.0
26,2025-01-07,EFL Cup,Arsenal,Alexander Isak,Y,FW,64.0,Away,W 2–0,77.0,226.0
28,2025-01-15,Premier League,Wolves,Alexander Isak,Y,FW,77.0,Home,W 3–0,79.0,246.0
29,2025-01-18,Premier League,Bournemouth,Alexander Isak,Y,"FW,LW",90.0,Home,L 1–4,90.0,169.0
30,2025-01-25,Premier League,Southampton,Alexander Isak,Y,FW,79.0,Away,W 3–1,176.0,255.0
31,2025-02-01,Premier League,Fulham,Alexander Isak,Y,FW,90.0,Home,L 1–2,87.0,177.0
32,2025-02-05,EFL Cup,Arsenal,Alexander Isak,Y,FW,86.0,Home,W 2–0,89.0,176.0
33,2025-02-08,FA Cup,Birmingham City,Alexander Isak,N,NaN,1.0,Away,W 3–2,86.0,175.0
34,2025-02-15,Premier League,Manchester City,Alexander Isak,Y,"FW,LW",89.0,Away,L 0–4,85.0,171.0
35,2025-02-23,Premier League,Nott'ham Forest,Alexander Isak,Y,FW,86.0,Home,W 4–3,78.0,163.0
37,2025-03-02,FA Cup,Brighton,Alexander Isak,Y,FW,85.0,Home,L 1–2,140.0,218.0
38,2025-03-10,Premier League,West Ham,Alexander Isak,Y,FW,78.0,Away,W 1–0,150.0,230.0
39,2025-03-16,EFL Cup,Liverpool,Alexander Isak,Y,FW,80.0,Neutral,W 2–1,65.0,215.0
40,2025-03-22,Friendlies (M),lu Luxembourg,Alexander Isak,Y*,FW,60.0,Away,L 0–1,136.0,226.0
41,2025-03-25,Friendlies (M),nir Northern Ireland,Alexander Isak,Y,FW,90.0,Home,W 5–1,148.0,213.0
42,2025-04-02,Premier League,Brentford,Alexander Isak,Y,FW,65.0,Home,W 2–1,148.0,219.0
43,2025-04-07,Premier League,Leicester City,Alexander Isak,Y,FW,71.0,Away,W 3–0,223.0,294.0
44,2025-04-13,Premier League,Manchester Utd,Alexander Isak,Y,FW,77.0,Home,W 4–1,76.0,299.0
45,2025-04-16,Premier League,Crystal Palace,Alexander Isak,Y,FW,71.0,Home,W 5–0,90.0,166.0
46,2025-04-19,Premier League,Aston Villa,Alexander Isak,Y,FW,75.0,Away,L 1–4,89.0,179.0
47,2025-04-26,Premier League,Ipswich Town,Alexander Isak,Y,FW,76.0,Home,W 3–0,90.0,90.0
48,2025-05-04,Premier League,Brighton,Alexander Isak,Y,"FW,AM",90.0,Away,D 1–1,NaN,NaN
49,2025-05-11,Premier League,Chelsea,Alexander Isak,Y,FW,89.0,Home,W 2–0,NaN,NaN
51,2025-05-25,Premier League,Everton,Alexander Isak,Y,"FW,LW",90.0,Home,L 0–1,NaN,NaN

In [182]:
ai_player_cols.loc[ai_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
ai_player_cols["Date"] = pd.to_datetime(ai_player_cols["Date"], format="%Y-%m-%d")

ai_player_cols.sort_values(by=["Player","Date"])

ai_player_cols["7D Rolling Avg"] = ai_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
ai_player_cols["14D Rolling Avg"] = ai_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [184]:
ai_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-17,Premier League,Southampton,Alexander Isak,Y,FW,90.0,Home,W 1–0,90.0,90.0
1,2024-08-25,Premier League,Bournemouth,Alexander Isak,Y,FW,90.0,Away,D 1–1,90.0,180.0
2,2024-08-28,EFL Cup,Nott'ham Forest,Alexander Isak,Y,FW,90.0,Away,D 1 (4)–1 (3),180.0,270.0
3,2024-09-01,Premier League,Tottenham,Alexander Isak,Y,FW,90.0,Home,W 2–1,180.0,270.0
4,2024-09-05,UEFA Nations League,az Azerbaijan,Alexander Isak,Y,FW,90.0,Away,W 3–1,180.0,360.0

In [114]:
test_mk = pd.read_html('https://fbref.com/en/players/0ad53bdc/matchlogs/2024-2025/Milos-Kerkez-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [116]:
test_mk.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-08-17                Sat       Premier League
1         2024-08-25                Sun       Premier League
2         2024-08-28                Wed              EFL Cup
3         2024-08-31                Sat       Premier League
4         2024-09-07                Sat  UEFA Nations League

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Round              Venue             Result              Squad
0        Matchweek 1               Away              D 1–1        Bournemouth
1        Matchweek 2               Home              D 1–1        Bournemouth
2       Second round               Away              L 0–1        Bournemouth
3        Matchweek 3               Away              W 3–2        Bournemouth
4           League A               Away              L 0–5         hu Hungary

  Unnamed: 7_level_0 Unnamed: 8_level_0                   Unnamed: 9_level_0  \
            Opponent              Start                                  Pos
0    Nott'ham Forest                  Y                                   LB
1      Newcastle Utd                  Y                                   LB
2           West Ham                  N  On matchday squad, but did not play
3            Everton                  Y                                   LB
4         de Germany                  Y                                   DM

   ...                                  SCA  \
   ...                                  GCA
0  ...                                    1
1  ...                                    0
2  ...  On matchday squad, but did not play
3  ...                                    0
4  ...                                  NaN

                                Passes                                       \
                                   Cmp                                  Att
0                                   46                                   56
1                                   25                                   37
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                   20                                   30
4                                  NaN                                  NaN

                                                                             \
                                  Cmp%                                 PrgP
0                                 82.1                                    8
1                                 67.6                                    3
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                 66.7                                    3
4                                  NaN                                  NaN

                               Carries                                       \
                               Carries                                 PrgC
0                                   33                                    4
1                                   16                                    0
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                   13                                    3
4                                  NaN                                  NaN

                              Take-Ons                                       \
                                   Att                                 Succ
0                                    0                                    0
1                                    0                                    0
2  On matchday squad, but did not play  On matchday squad, but did not play
3                                    0                                    0
4                                  NaN                                  NaN

  Unnamed: 36_level_0
         Match Report
0        Match Report
1        Match Report
2        Match Report
3        Match Report
4        Match Report

[5 rows x 37 columns]

In [118]:
mk_player_cols = pd.DataFrame()

In [120]:
mk_player_cols['Date'] = test_mk['Unnamed: 0_level_0']['Date'].copy()
mk_player_cols['Competition'] = test_mk['Unnamed: 2_level_0']['Comp'].copy()
mk_player_cols['Opponent'] = test_mk['Unnamed: 7_level_0']['Opponent'].copy()
mk_player_cols['Player'] = "Milos Kerkez"
mk_player_cols['Started the Game'] = test_mk['Unnamed: 8_level_0']['Start'].copy()
mk_player_cols['Position'] = test_mk['Unnamed: 9_level_0']['Pos'].copy()
mk_player_cols['Minutes'] = test_mk['Unnamed: 10_level_0']['Min'].copy()
mk_player_cols['Venue'] = test_mk['Unnamed: 4_level_0']['Venue'].copy()
mk_player_cols['Venue'] = test_mk['Unnamed: 4_level_0']['Venue'].copy()
mk_player_cols['Result'] = test_mk['Unnamed: 5_level_0']['Result'].copy()

In [122]:
mk_player_cols= mk_player_cols.dropna(subset=['Date'])

In [124]:
mk_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-08-17,Premier League,Nott'ham Forest,Milos Kerkez,Y,LB,90,Away,D 1–1
1,2024-08-25,Premier League,Newcastle Utd,Milos Kerkez,Y,LB,90,Home,D 1–1
2,2024-08-28,EFL Cup,West Ham,Milos Kerkez,N,"On matchday squad, but did not play","On matchday squad, but did not play",Away,L 0–1
3,2024-08-31,Premier League,Everton,Milos Kerkez,Y,LB,65,Away,W 3–2
4,2024-09-07,UEFA Nations League,de Germany,Milos Kerkez,Y,DM,66,Away,L 0–5

In [126]:
mk_player_cols.loc[mk_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0

In [130]:
mk_player_cols["Date"] = pd.to_datetime(mk_player_cols["Date"], format="%Y-%m-%d")

In [132]:
mk_player_cols.sort_values(by=["Player","Date"])

mk_player_cols["7D Rolling Avg"] = mk_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
mk_player_cols["14D Rolling Avg"] = mk_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [134]:
mk_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-17,Premier League,Nott'ham Forest,Milos Kerkez,Y,LB,90,Away,D 1–1,90.0,90.0
1,2024-08-25,Premier League,Newcastle Utd,Milos Kerkez,Y,LB,90,Home,D 1–1,90.0,180.0
2,2024-08-28,EFL Cup,West Ham,Milos Kerkez,N,"On matchday squad, but did not play",0,Away,L 0–1,90.0,180.0
3,2024-08-31,Premier League,Everton,Milos Kerkez,Y,LB,65,Away,W 3–2,155.0,155.0
4,2024-09-07,UEFA Nations League,de Germany,Milos Kerkez,Y,DM,66,Away,L 0–5,66.0,221.0

In [138]:
test_jg = pd.read_html('https://fbref.com/en/players/5ad50391/matchlogs/2024-2025/Josko-Gvardiol-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [140]:
test_jg.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                Date                Day                 Comp
0         2024-08-10                Sat  FA Community Shield
1         2024-08-18                Sun       Premier League
2         2024-08-24                Sat       Premier League
3         2024-08-31                Sat       Premier League
4         2024-09-05                Thu  UEFA Nations League

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                 Round              Venue             Result
0  FA Community Shield               Home      D 1 (7)–1 (6)
1          Matchweek 1               Away              W 2–0
2          Matchweek 2               Home              W 4–1
3          Matchweek 3               Away              W 3–1
4             League A               Away              L 1–2

  Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  \
               Squad           Opponent              Start                Pos
0    Manchester City     Manchester Utd                  Y                 LB
1    Manchester City            Chelsea                  Y                 LB
2    Manchester City       Ipswich Town                  Y                 LB
3    Manchester City           West Ham                  Y                 LB
4         hr Croatia        pt Portugal                  Y                 CB

   ...  SCA Passes                 Carries      Take-Ons       \
   ...  GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0  ...  NaN    NaN  NaN   NaN  NaN     NaN  NaN      NaN  NaN
1  ...    0     64   69  92.8    5      46    3        1    1
2  ...    0     92   99  92.9   10      65    3        2    1
3  ...    0     58   61  95.1    9      37    0        1    1
4  ...  NaN    NaN  NaN   NaN  NaN     NaN  NaN      NaN  NaN

  Unnamed: 36_level_0
         Match Report
0        Match Report
1        Match Report
2        Match Report
3        Match Report
4        Match Report

[5 rows x 37 columns]

In [142]:
jg_player_cols = pd.DataFrame()

In [144]:
jg_player_cols['Date'] = test_jg['Unnamed: 0_level_0']['Date'].copy()
jg_player_cols['Competition'] = test_jg['Unnamed: 2_level_0']['Comp'].copy()
jg_player_cols['Opponent'] = test_jg['Unnamed: 7_level_0']['Opponent'].copy()
jg_player_cols['Player'] = "Josko Gvardiol"
jg_player_cols['Started the Game'] = test_jg['Unnamed: 8_level_0']['Start'].copy()
jg_player_cols['Position'] = test_jg['Unnamed: 9_level_0']['Pos'].copy()
jg_player_cols['Minutes'] = test_jg['Unnamed: 10_level_0']['Min'].copy()
jg_player_cols['Venue'] = test_jg['Unnamed: 4_level_0']['Venue'].copy()
jg_player_cols['Venue'] = test_jg['Unnamed: 4_level_0']['Venue'].copy()
jg_player_cols['Result'] = test_jg['Unnamed: 5_level_0']['Result'].copy()

In [146]:
jg_player_cols= jg_player_cols.dropna(subset=['Date'])

In [148]:
jg_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-08-10,FA Community Shield,Manchester Utd,Josko Gvardiol,Y,LB,89,Home,D 1 (7)–1 (6)
1,2024-08-18,Premier League,Chelsea,Josko Gvardiol,Y,LB,90,Away,W 2–0
2,2024-08-24,Premier League,Ipswich Town,Josko Gvardiol,Y,LB,90,Home,W 4–1
3,2024-08-31,Premier League,West Ham,Josko Gvardiol,Y,LB,87,Away,W 3–1
4,2024-09-05,UEFA Nations League,pt Portugal,Josko Gvardiol,Y,CB,90,Away,L 1–2

In [150]:
jg_player_cols.loc[jg_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
jg_player_cols["Date"] = pd.to_datetime(jg_player_cols["Date"], format="%Y-%m-%d")

jg_player_cols.sort_values(by=["Player","Date"])

jg_player_cols["7D Rolling Avg"] = jg_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
jg_player_cols["14D Rolling Avg"] = jg_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [152]:
jg_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-08-10,FA Community Shield,Manchester Utd,Josko Gvardiol,Y,LB,89,Home,D 1 (7)–1 (6),89.0,89.0
1,2024-08-18,Premier League,Chelsea,Josko Gvardiol,Y,LB,90,Away,W 2–0,90.0,179.0
2,2024-08-24,Premier League,Ipswich Town,Josko Gvardiol,Y,LB,90,Home,W 4–1,180.0,180.0
3,2024-08-31,Premier League,West Ham,Josko Gvardiol,Y,LB,87,Away,W 3–1,87.0,267.0
4,2024-09-05,UEFA Nations League,pt Portugal,Josko Gvardiol,Y,CB,90,Away,L 1–2,177.0,267.0

In [550]:
test_dm = pd.read_html('https://fbref.com/en/players/778ef829/matchlogs/2024-2025/Daniel-Munoz-Match-Logs', 
                 attrs ={"id" : "matchlogs_all"})[0]

In [552]:
test_dm.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Date                Day               Comp              Round
0         2024-07-02                Tue       Copa América        Group stage
1         2024-07-06                Sat       Copa América     Quarter-finals
2         2024-07-10                Wed       Copa América        Semi-finals
3         2024-08-18                Sun     Premier League        Matchweek 1
4         2024-08-24                Sat     Premier League        Matchweek 2

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
               Venue             Result              Squad           Opponent
0            Neutral              D 1–1        co Colombia          br Brazil
1            Neutral              W 5–0        co Colombia          pa Panama
2            Neutral              W 1–0        co Colombia         uy Uruguay
3               Away              L 1–2     Crystal Palace          Brentford
4               Home              L 0–2     Crystal Palace           West Ham

  Unnamed: 8_level_0 Unnamed: 9_level_0  ...  SCA Passes                   \
               Start                Pos  ...  GCA    Cmp   Att  Cmp% PrgP
0                  Y                 RB  ...  0.0   35.0  37.0  94.6  5.0
1                  Y                 RB  ...  1.0   23.0  27.0  85.2  1.0
2                  Y                 RB  ...  1.0   21.0  23.0  91.3  1.0
3                  Y              WB,RB  ...  0.0   42.0  55.0  76.4  1.0
4                  Y                 WB  ...  0.0   48.0  59.0  81.4  2.0

  Carries      Take-Ons      Unnamed: 36_level_0
  Carries PrgC      Att Succ        Match Report
0    23.0  0.0      2.0  0.0        Match Report
1    17.0  1.0      0.0  0.0        Match Report
2     9.0  1.0      1.0  0.0        Match Report
3    25.0  0.0      3.0  0.0        Match Report
4    34.0  1.0      2.0  1.0        Match Report

[5 rows x 37 columns]

In [554]:
dm_player_cols = pd.DataFrame()

In [556]:
dm_player_cols['Date'] = test_dm['Unnamed: 0_level_0']['Date'].copy()
dm_player_cols['Competition'] = test_dm['Unnamed: 2_level_0']['Comp'].copy()
dm_player_cols['Opponent'] = test_dm['Unnamed: 7_level_0']['Opponent'].copy()
dm_player_cols['Player'] = "Daniel Munoz"
dm_player_cols['Started the Game'] = test_dm['Unnamed: 8_level_0']['Start'].copy()
dm_player_cols['Position'] = test_dm['Unnamed: 9_level_0']['Pos'].copy()
dm_player_cols['Minutes'] = test_dm['Unnamed: 10_level_0']['Min'].copy()
dm_player_cols['Venue'] = test_dm['Unnamed: 4_level_0']['Venue'].copy()
dm_player_cols['Result'] = test_dm['Unnamed: 5_level_0']['Result'].copy()

In [558]:
dm_player_cols= dm_player_cols.dropna(subset=['Date'])

In [570]:
dm_player_cols.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-02,Copa América,br Brazil,Daniel Munoz,Y,RB,90,Neutral,D 1–1,90.0,90.0
1,2024-07-06,Copa América,pa Panama,Daniel Munoz,Y,RB,72,Neutral,W 5–0,162.0,162.0
2,2024-07-10,Copa América,uy Uruguay,Daniel Munoz,Y,RB,44,Neutral,W 1–0,116.0,206.0
3,2024-08-18,Premier League,Brentford,Daniel Munoz,Y,"WB,RB",90,Away,L 1–2,90.0,90.0
4,2024-08-24,Premier League,West Ham,Daniel Munoz,Y,WB,90,Home,L 0–2,180.0,180.0

In [564]:
dm_player_cols["Minutes"] = dm_player_cols["Minutes"].astype("int32")

In [566]:
dm_player_cols.loc[dm_player_cols["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
dm_player_cols["Date"] = pd.to_datetime(dm_player_cols["Date"], format="%Y-%m-%d")

dm_player_cols.sort_values(by=["Player","Date"])

dm_player_cols["7D Rolling Avg"] = dm_player_cols.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
dm_player_cols["14D Rolling Avg"] = dm_player_cols.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [572]:
dm_player_cols[dm_player_cols["7D Rolling Avg"].isna()]

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
57,2025-06-10,WCQ,ar Argentina,Daniel Munoz,Y,RB,90,Away,D 1–1,NaN,NaN

In [588]:
x = dm_player_cols.head().copy()

In [596]:
y = dm_player_cols.tail().copy()

In [590]:
x["7D Rolling Avg"] = x.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
x["14D Rolling Avg"] = x.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [612]:
y["7D Rolling Avg"] = y.groupby("Player").rolling(window="7D", on="Date")["Minutes"].sum().reset_index(drop=True)
y["14D Rolling Avg"] = y.groupby("Player").rolling(window="14D", on="Date")["Minutes"].sum().reset_index(drop=True)

In [600]:
x

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-02,Copa América,br Brazil,Daniel Munoz,Y,RB,90,Neutral,D 1–1,90.0,90.0
1,2024-07-06,Copa América,pa Panama,Daniel Munoz,Y,RB,72,Neutral,W 5–0,162.0,162.0
2,2024-07-10,Copa América,uy Uruguay,Daniel Munoz,Y,RB,44,Neutral,W 1–0,116.0,206.0
3,2024-08-18,Premier League,Brentford,Daniel Munoz,Y,"WB,RB",90,Away,L 1–2,90.0,90.0
4,2024-08-24,Premier League,West Ham,Daniel Munoz,Y,WB,90,Home,L 0–2,180.0,180.0

In [606]:
y

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
53,2025-05-17,FA Cup,Manchester City,Daniel Munoz,Y,DM,90,Neutral,W 1–0,NaN,NaN
54,2025-05-20,Premier League,Wolves,Daniel Munoz,Y,WB,90,Home,W 4–2,NaN,NaN
55,2025-05-25,Premier League,Liverpool,Daniel Munoz,Y,WB,90,Away,D 1–1,NaN,NaN
56,2025-06-06,WCQ,pe Peru,Daniel Munoz,Y,RB,90,Home,D 0–0,NaN,NaN
57,2025-06-10,WCQ,ar Argentina,Daniel Munoz,Y,RB,90,Away,D 1–1,NaN,NaN

In [594]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              5 non-null      datetime64[ns]
 1   Competition       5 non-null      object
 2   Opponent          5 non-null      object
 3   Player            5 non-null      object
 4   Started the Game  5 non-null      object
 5   Position          5 non-null      object
 6   Minutes           5 non-null      int32
 7   Venue             5 non-null      object
 8   Result            5 non-null      object
 9   7D Rolling Avg    5 non-null      float64
 10  14D Rolling Avg   5 non-null      float64
dtypes: datetime64[ns](1), float64(2), int32(1), object(7)
memory usage: 460.0+ bytes

In [358]:
source = pd.DataFrame()

In [260]:
source = pd.concat([player_cols,mc_player_cols], ignore_index=True)
source

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result
0,2024-07-01,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1
1,2024-08-10,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NaN,1,Home,D 1 (7)–1 (6)
2,2024-08-18,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0
3,2024-08-24,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1
4,2024-08-31,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1
...,...,...,...,...,...,...,...,...,...
112,2025-06-10,WCQ,pe Peru,Moises Caicedo,Y,CM,90,Away,D 0–0
113,2025-06-16,Club World Cup,us LAFC,Moises Caicedo,Y,DM,82,Neutral,W 2–0
114,2025-06-20,Club World Cup,br Flamengo,Moises Caicedo,Y,DM,90,Neutral,L 1–3
115,2025-06-24,Club World Cup,tn Espérance Tunis,Moises Caicedo,N,"On matchday squad, but did not play","On matchday squad, but did not play",Neutral,W 3–0
116,2025-06-28,Club World Cup,pt Benfica,Moises Caicedo,Y,DM,120,Neutral,W 4–1

In [262]:
[t for t in globals() if isinstance(globals()[t], pd.DataFrame)]

['___',
 'df',
 '_9',
 '_17',
 '_27',
 '_29',
 '_53',
 'test',
 '_69',
 'player_cols',
 '_81',
 '_85',
 '_90',
 '_94',
 '_96',
 '_98',
 '_100',
 '_102',
 'test_mc',
 '_106',
 'mc_player_cols',
 '_114',
 '_116',
 'test_bg',
 '_120',
 'bg_player_cols',
 '_126',
 '_128',
 'test_rg',
 '_132',
 'rg_player_cols',
 '_138',
 '_140',
 'test_yt',
 '_144',
 'yt_player_cols',
 '_150',
 '_152',
 'test_bf',
 '_156',
 'bf_player_cols',
 '_162',
 'test_mr',
 '_176',
 'mr_player_cols',
 '_184',
 'test_bm',
 '_188',
 'bm_player_cols',
 '_194',
 'test_ms',
 '_200',
 'ms_player_cols',
 '_208',
 'test_ai',
 '_212',
 'ai_player_cols',
 '_220',
 'test_mk',
 '_224',
 'mk_player_cols',
 '_232',
 'test_jg',
 '_236',
 'jg_player_cols',
 '_244',
 'test_dm',
 '_248',
 'dm_player_cols',
 '_256',
 'source',
 '_260']

In [360]:
source = pd.concat([player_cols,mc_player_cols,bg_player_cols,rg_player_cols,yt_player_cols,bf_player_cols,mr_player_cols,bm_player_cols,ms_player_cols,ai_player_cols,mk_player_cols,jg_player_cols,dm_player_cols]
                   , ignore_index=True)
source

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0
1,2024-08-10,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NaN,1,Home,D 1 (7)–1 (6),1.0,1.0
2,2024-08-18,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0
3,2024-08-24,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0
4,2024-08-31,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0
...,...,...,...,...,...,...,...,...,...,...,...
746,2025-05-17,FA Cup,Manchester City,Daniel Munoz,Y,DM,90.0,Neutral,W 1–0,180.0,270.0
747,2025-05-20,Premier League,Wolves,Daniel Munoz,Y,WB,90.0,Home,W 4–2,180.0,270.0
748,2025-05-25,Premier League,Liverpool,Daniel Munoz,Y,WB,90.0,Away,D 1–1,90.0,180.0
749,2025-06-06,WCQ,pe Peru,Daniel Munoz,Y,RB,90.0,Home,D 0–0,180.0,180.0
750,2025-06-10,WCQ,ar Argentina,Daniel Munoz,Y,RB,90.0,Away,D 1–1,NaN,NaN

In [364]:
source.to_excel("Source_Player_Data.xlsx", sheet_name="Source_Player_Data", index=False)

In [366]:
source.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              751 non-null    datetime64[ns]
 1   Competition       751 non-null    object
 2   Opponent          751 non-null    object
 3   Player            751 non-null    object
 4   Started the Game  751 non-null    object
 5   Position          724 non-null    object
 6   Minutes           751 non-null    object
 7   Venue             751 non-null    object
 8   Result            751 non-null    object
 9   7D Rolling Avg    716 non-null    float64
 10  14D Rolling Avg   716 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(8)
memory usage: 64.7+ KB

In [286]:
source["Date"] = pd.to_datetime(source["Date"], format="%Y-%m-%d")

In [357]:
source.loc[source["Position"]=="On matchday squad, but did not play","Position"] = 0

In [359]:
source["Position"].value_counts()

Position
DM          131
AM           81
CM           80
LB           76
RW           73
FW           57
0            51
WB           24
CB           17
RM           15
DM,CM        14
AM,CM        12
RB           11
CM,AM        11
LW            7
RW,FW         7
LB,CB         6
RW,LW         6
WB,RB         6
AM,DM         5
WB,AM         4
FW,LW         4
FW,AM         4
DM,CB         3
CB,LB         3
LW,RW         3
RB,DM         3
AM,LM         2
RW,RM         2
RM,LM         2
CM,LM         2
RW,AM         2
RW,WB         2
DM,RB         2
CM,DM         2
AM,FW,RW      1
RM,RB         1
LM            1
RM,RW         1
LB,WB         1
AM,FW         1
RW,LW,RM      1
AM,RW,FW      1
LW,LM,FW      1
AM,LM,LW      1
LW,CM         1
DM,FW,AM      1
DM,AM         1
DM,RM         1
CB,CM,DM      1
RM,CM         1
RM,DM         1
RB,CM,CB      1
RB,CM         1
AM,CM,DM      1
WB,CB         1
Name: count, dtype: int64

In [2]:
import pandas as pd
import matplotlib as plt

In [7]:
source = pd.read_excel("Source_Player_Data.xlsx",parse_dates=["Date"], date_format="%Y-%m-%d")

In [9]:
source.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01 00:00:00,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0
1,2024-08-10 00:00:00,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NaN,1,Home,D 1 (7)–1 (6),1.0,1.0
2,2024-08-18 00:00:00,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0
3,2024-08-24 00:00:00,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0
4,2024-08-31 00:00:00,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0

In [11]:
source.loc[source["Position"]=="On matchday squad, but did not play","Position"] = 0
source.loc[source["Position"].isna(),"Position"] = "NULL"
source.loc[source["Minutes"] == "On matchday squad, but did not play", "Minutes"] = 0
source["Minutes"] = pd.to_numeric(source["Minutes"], errors="coerce")

In [13]:
source.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              751 non-null    object
 1   Competition       751 non-null    object
 2   Opponent          751 non-null    object
 3   Player            751 non-null    object
 4   Started the Game  751 non-null    object
 5   Position          751 non-null    object
 6   Minutes           751 non-null    int64
 7   Venue             751 non-null    object
 8   Result            751 non-null    object
 9   7D Rolling Avg    716 non-null    float64
 10  14D Rolling Avg   716 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 64.7+ KB

In [15]:
source.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg
0,2024-07-01 00:00:00,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0
1,2024-08-10 00:00:00,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NULL,1,Home,D 1 (7)–1 (6),1.0,1.0
2,2024-08-18 00:00:00,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0
3,2024-08-24 00:00:00,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0
4,2024-08-31 00:00:00,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0

In [17]:
source["Overall Result"] = source["Result"].apply(lambda x: x.split(" ")[0])

In [19]:
source.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result
0,2024-07-01 00:00:00,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0,L
1,2024-08-10 00:00:00,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NULL,1,Home,D 1 (7)–1 (6),1.0,1.0,D
2,2024-08-18 00:00:00,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0,W
3,2024-08-24 00:00:00,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0,W
4,2024-08-31 00:00:00,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0,W

In [21]:
source.loc[source["Position"] == 0,"Position"] = "NULL"

In [23]:
source

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result
0,2024-07-01 00:00:00,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0,L
1,2024-08-10 00:00:00,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NULL,1,Home,D 1 (7)–1 (6),1.0,1.0,D
2,2024-08-18 00:00:00,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0,W
3,2024-08-24 00:00:00,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0,W
4,2024-08-31 00:00:00,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0,W
...,...,...,...,...,...,...,...,...,...,...,...,...
746,2025-05-17 00:00:00,FA Cup,Manchester City,Daniel Munoz,Y,DM,90,Neutral,W 1–0,180.0,270.0,W
747,2025-05-20 00:00:00,Premier League,Wolves,Daniel Munoz,Y,WB,90,Home,W 4–2,180.0,270.0,W
748,2025-05-25 00:00:00,Premier League,Liverpool,Daniel Munoz,Y,WB,90,Away,D 1–1,90.0,180.0,D
749,2025-06-06 00:00:00,WCQ,pe Peru,Daniel Munoz,Y,RB,90,Home,D 0–0,180.0,180.0,D
750,2025-06-10 00:00:00,WCQ,ar Argentina,Daniel Munoz,Y,RB,90,Away,D 1–1,NaN,NaN,D

In [25]:
position_load_map = {
    # Defensive positions
    "CB": 2,
    "LB": 3,
    "RB": 3,
    "WB": 3,

    # Midfield positions
    "DM": 4,
    "CM": 4,
    "AM": 4,
    "LM": 4,
    "RM": 4,

    # Attacking positions
    "RW": 4,
    "LW": 4,
    "FW": 3,

    # fallback cases
    "GK": 1,   
    "NULL": 2     
}

source["Primary Position"] = source["Position"].fillna("").apply(lambda x: x.split(",")[0].strip())

source["Position Load Score"] = source["Primary Position"].map(position_load_map).fillna(2).astype(int)

In [27]:
source.head()

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
0,2024-07-01 00:00:00,UEFA Euro,fr France,Kevin De Bruyne,Y*,"CM,AM",90,Neutral,L 0–1,90.0,90.0,L,CM,4
1,2024-08-10 00:00:00,FA Community Shield,Manchester Utd,Kevin De Bruyne,N,NULL,1,Home,D 1 (7)–1 (6),1.0,1.0,D,NULL,2
2,2024-08-18 00:00:00,Premier League,Chelsea,Kevin De Bruyne,Y*,CM,90,Away,W 2–0,90.0,91.0,W,CM,4
3,2024-08-24 00:00:00,Premier League,Ipswich Town,Kevin De Bruyne,Y*,"CM,AM",89,Home,W 4–1,179.0,179.0,W,CM,4
4,2024-08-31 00:00:00,Premier League,West Ham,Kevin De Bruyne,Y*,CM,87,Away,W 3–1,87.0,266.0,W,CM,4

In [29]:
source["Venue"].value_counts()

Venue
Home       367
Away       348
Neutral     36
Name: count, dtype: int64

In [31]:
source.loc[source["Started the Game"] == "Y*","Started the Game"] = "Y"

In [33]:
source["Started the Game"].value_counts()

Started the Game
Y    684
N     67
Name: count, dtype: int64

In [35]:
source["Started the Game"] = source["Started the Game"].astype("category")

In [37]:
source["Venue"] = source["Venue"].astype("category")

In [39]:
source.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 751 non-null    object
 1   Competition          751 non-null    object
 2   Opponent             751 non-null    object
 3   Player               751 non-null    object
 4   Started the Game     751 non-null    category
 5   Position             751 non-null    object
 6   Minutes              751 non-null    int64
 7   Venue                751 non-null    category
 8   Result               751 non-null    object
 9   7D Rolling Avg       716 non-null    float64
 10  14D Rolling Avg      716 non-null    float64
 11  Overall Result       751 non-null    object
 12  Primary Position     751 non-null    object
 13  Position Load Score  751 non-null    int32
dtypes: category(2), float64(2), int32(1), int64(1), object(8)
memory usage: 69.3+ KB

In [398]:
source.to_excel("Modified_Source.xlsx",index=False)

In [ ]:
source = pd.read_excel

In [41]:
source.sort_values(by=["Player","Date"])

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
530,2024-08-17 00:00:00,Premier League,Southampton,Alexander Isak,Y,FW,90,Home,W 1–0,90.0,90.0,W,FW,3
531,2024-08-25 00:00:00,Premier League,Bournemouth,Alexander Isak,Y,FW,90,Away,D 1–1,90.0,180.0,D,FW,3
532,2024-08-28 00:00:00,EFL Cup,Nott'ham Forest,Alexander Isak,Y,FW,90,Away,D 1 (4)–1 (3),180.0,270.0,D,FW,3
533,2024-09-01 00:00:00,Premier League,Tottenham,Alexander Isak,Y,FW,90,Home,W 2–1,180.0,270.0,W,FW,3
534,2024-09-05 00:00:00,UEFA Nations League,az Azerbaijan,Alexander Isak,Y,FW,90,Away,W 3–1,180.0,360.0,W,FW,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,2025-04-26 00:00:00,FA Cup,Crystal Palace,Youri Tielemans,Y,DM,90,Away,L 0–3,29.0,29.0,L,DM,4
292,2025-05-03 00:00:00,Premier League,Fulham,Youri Tielemans,Y,"DM,FW,AM",82,Home,W 1–0,35.0,64.0,W,DM,4
293,2025-05-25 00:00:00,Premier League,Manchester Utd,Youri Tielemans,N,DM,29,Away,L 0–2,NaN,NaN,L,DM,4
294,2025-06-06 00:00:00,WCQ,mk N. Macedonia,Youri Tielemans,N,NULL,35,Away,D 1–1,NaN,NaN,D,NULL,2
295,2025-06-09 00:00:00,WCQ,wls Wales,Youri Tielemans,Y,DM,90,Home,W 4–3,NaN,NaN,W,DM,4

In [43]:
source[source["7D Rolling Avg"].isna()]

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
54,2025-06-09 00:00:00,WCQ,wls Wales,Kevin De Bruyne,Y,AM,88,Home,W 4–3,NaN,NaN,W,AM,4
108,2025-05-16 00:00:00,Premier League,Manchester Utd,Moises Caicedo,Y,DM,90,Home,W 1–0,NaN,NaN,W,DM,4
109,2025-05-25 00:00:00,Premier League,Nott'ham Forest,Moises Caicedo,Y,"DM,CM",90,Away,W 1–0,NaN,NaN,W,DM,4
110,2025-05-28 00:00:00,Conf Lg,es Betis,Moises Caicedo,Y,DM,90,Neutral,W 4–1,NaN,NaN,W,DM,4
111,2025-06-05 00:00:00,WCQ,br Brazil,Moises Caicedo,Y,CM,90,Home,D 0–0,NaN,NaN,D,CM,4
112,2025-06-10 00:00:00,WCQ,pe Peru,Moises Caicedo,Y,CM,90,Away,D 0–0,NaN,NaN,D,CM,4
113,2025-06-16 00:00:00,Club World Cup,us LAFC,Moises Caicedo,Y,DM,82,Neutral,W 2–0,NaN,NaN,W,DM,4
114,2025-06-20 00:00:00,Club World Cup,br Flamengo,Moises Caicedo,Y,DM,90,Neutral,L 1–3,NaN,NaN,L,DM,4
115,2025-06-24 00:00:00,Club World Cup,tn Espérance Tunis,Moises Caicedo,N,NULL,0,Neutral,W 3–0,NaN,NaN,W,NULL,2
116,2025-06-28 00:00:00,Club World Cup,pt Benfica,Moises Caicedo,Y,DM,120,Neutral,W 4–1,NaN,NaN,W,DM,4
174,2025-06-10 00:00:00,WCQ,py Paraguay,Bruno Guimaraes,Y,DM,90,Home,W 1–0,NaN,NaN,W,DM,4
229,2025-04-27 00:00:00,Premier League,Tottenham,Ryan Gravenberch,Y,DM,90,Home,W 5–1,NaN,NaN,W,DM,4
230,2025-05-11 00:00:00,Premier League,Arsenal,Ryan Gravenberch,Y,DM,82,Home,D 2–2,NaN,NaN,D,DM,4
231,2025-05-19 00:00:00,Premier League,Brighton,Ryan Gravenberch,Y,DM,90,Away,L 2–3,NaN,NaN,L,DM,4
232,2025-05-25 00:00:00,Premier League,Crystal Palace,Ryan Gravenberch,Y,"DM,CB",67,Home,D 1–1,NaN,NaN,D,DM,4
233,2025-06-07 00:00:00,WCQ,fi Finland,Ryan Gravenberch,Y,CM,90,Away,W 2–0,NaN,NaN,W,CM,4
234,2025-06-10 00:00:00,WCQ,mt Malta,Ryan Gravenberch,Y,CM,45,Home,W 8–0,NaN,NaN,W,CM,4
293,2025-05-25 00:00:00,Premier League,Manchester Utd,Youri Tielemans,N,DM,29,Away,L 0–2,NaN,NaN,L,DM,4
294,2025-06-06 00:00:00,WCQ,mk N. Macedonia,Youri Tielemans,N,NULL,35,Away,D 1–1,NaN,NaN,D,NULL,2
295,2025-06-09 00:00:00,WCQ,wls Wales,Youri Tielemans,Y,DM,90,Home,W 4–3,NaN,NaN,W,DM,4
363,2025-06-04 00:00:00,UEFA Nations League,de Germany,Bruno Fernandes,Y,CM,90,Neutral,W 2–1,NaN,NaN,W,CM,4
364,2025-06-08 00:00:00,UEFA Nations League,es Spain,Bruno Fernandes,Y,CM,120,Neutral,D 2 (5)–2 (3),NaN,NaN,D,CM,4
422,2025-05-25 00:00:00,Premier League,Manchester Utd,Morgan Rogers,Y,RW,83,Away,L 0–2,NaN,NaN,L,RW,4
423,2025-06-07 00:00:00,WCQ,ad Andorra,Morgan Rogers,Y,LB,79,Away,W 1–0,NaN,NaN,W,LB,3
424,2025-06-10 00:00:00,Friendlies (M),sn Senegal,Morgan Rogers,N,NULL,32,Home,L 1–3,NaN,NaN,L,NULL,2
472,2025-05-25 00:00:00,Premier League,Wolves,Bryan Mbeumo,Y,RW,90,Away,D 1–1,NaN,NaN,D,RW,4
526,2025-05-04 00:00:00,Premier League,Chelsea,Mohamed Salah,Y,RW,90,Away,L 1–3,NaN,NaN,L,RW,4
527,2025-05-11 00:00:00,Premier League,Arsenal,Mohamed Salah,Y,RW,90,Home,D 2–2,NaN,NaN,D,RW,4
528,2025-05-19 00:00:00,Premier League,Brighton,Mohamed Salah,Y,RW,90,Away,L 2–3,NaN,NaN,L,RW,4
529,2025-05-25 00:00:00,Premier League,Crystal Palace,Mohamed Salah,Y,"RW,RM",90,Home,D 1–1,NaN,NaN,D,RW,4
575,2025-05-04 00:00:00,Premier League,Brighton,Alexander Isak,Y,"FW,AM",90,Away,D 1–1,NaN,NaN,D,FW,3
576,2025-05-11 00:00:00,Premier League,Chelsea,Alexander Isak,Y,FW,89,Home,W 2–0,NaN,NaN,W,FW,3
577,2025-05-25 00:00:00,Premier League,Everton,Alexander Isak,Y,"FW,LW",90,Home,L 0–1,NaN,NaN,L,FW,3
693,2025-06-30 00:00:00,Club World Cup,sa Al-Hilal,Josko Gvardiol,Y,CB,52,Neutral,L 3–4,NaN,NaN,L,CB,2
750,2025-06-10 00:00:00,WCQ,ar Argentina,Daniel Munoz,Y,RB,90,Away,D 1–1,NaN,NaN,D,RB,3

In [49]:
source["Date"] = pd.to_datetime(source["Date"])
source = source.sort_values(["Player","Date"])

source["7D Rolling Avg"] = (
    source
    .groupby("Player")
    .rolling(window="7D", on="Date")["Minutes"]
    .sum()
    .reset_index(level=0, drop=True)
)

ValueError: cannot reindex on an axis with duplicate labels

In [55]:
# ensure sorted by Player and Date
source = source.sort_values(["Player","Date"]).reset_index(drop=True)

rolling_vals = []
for player, grp in source.groupby("Player"):
    grp = grp.set_index("Date").sort_index()
    # this is an array of length grp.shape[0]
    roll7 = grp["Minutes"].rolling("14D").sum().values
    rolling_vals.extend(roll7)

source["14D Rolling Avg"] = rolling_vals

In [61]:
source

,Date,Competition,Opponent,Player,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
0,2024-08-17,Premier League,Southampton,Alexander Isak,Y,FW,90,Home,W 1–0,90.0,90.0,W,FW,3
1,2024-08-25,Premier League,Bournemouth,Alexander Isak,Y,FW,90,Away,D 1–1,90.0,180.0,D,FW,3
2,2024-08-28,EFL Cup,Nott'ham Forest,Alexander Isak,Y,FW,90,Away,D 1 (4)–1 (3),180.0,270.0,D,FW,3
3,2024-09-01,Premier League,Tottenham,Alexander Isak,Y,FW,90,Home,W 2–1,180.0,270.0,W,FW,3
4,2024-09-05,UEFA Nations League,az Azerbaijan,Alexander Isak,Y,FW,90,Away,W 3–1,180.0,360.0,W,FW,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,2025-04-26,FA Cup,Crystal Palace,Youri Tielemans,Y,DM,90,Away,L 0–3,180.0,357.0,L,DM,4
747,2025-05-03,Premier League,Fulham,Youri Tielemans,Y,"DM,FW,AM",82,Home,W 1–0,82.0,262.0,W,DM,4
748,2025-05-25,Premier League,Manchester Utd,Youri Tielemans,N,DM,29,Away,L 0–2,29.0,29.0,L,DM,4
749,2025-06-06,WCQ,mk N. Macedonia,Youri Tielemans,N,NULL,35,Away,D 1–1,35.0,64.0,D,NULL,2
750,2025-06-09,WCQ,wls Wales,Youri Tielemans,Y,DM,90,Home,W 4–3,125.0,125.0,W,DM,4

In [63]:
source.to_excel("Modified_Source.xlsx",index=False)

In [4]:
source = pd.read_excel("Modified_Source.xlsx",parse_dates=["Date"], date_format="%Y-%m-%d")

In [10]:
season_dates = pd.date_range(start="2024-08-01", end="2025-05-31", freq="D")

In [12]:
match_days= season_dates[season_dates.dayofweek.isin([2,3,5,6])]

In [18]:
source.columns

Index(['Date', 'Competition', 'Opponent', 'Player', 'Started the Game',
       'Position', 'Minutes', 'Venue', 'Result', '7D Rolling Avg',
       '14D Rolling Avg', 'Overall Result', 'Primary Position',
       'Position Load Score'],
      dtype='object')

In [14]:
players = source["Player"].unique()
calendar = pd.MultiIndex.from_product([players, match_days], names=["Player", "Date"])
calendar_df = calendar.to_frame(index=False)

In [24]:
calendar.dtypes

Player            object
Date      datetime64[ns]
dtype: object

In [30]:
source.dtypes

Date                   object
Competition            object
Opponent               object
Player                 object
Started the Game       object
Position               object
Minutes                 int64
Venue                  object
Result                 object
7D Rolling Avg          int64
14D Rolling Avg         int64
Overall Result         object
Primary Position       object
Position Load Score     int64
dtype: object

In [36]:
source["Date"] = pd.to_datetime(source["Date"], format="mixed")

In [38]:
# original match logs: one row per match played
match_df = source[['Date', 'Competition', 'Opponent', 'Player', 'Started the Game',
       'Position', 'Minutes', 'Venue', 'Result', '7D Rolling Avg',
       '14D Rolling Avg', 'Overall Result', 'Primary Position',
       'Position Load Score']]  # all columns you want to keep

# Merge into calendar (left merge to preserve all rows)
full_df = calendar_df.merge(match_df, on=["Player", "Date"], how="left")

In [50]:
full_df[full_df["Player"] == "Alexander Isak"]

,Player,Date,Competition,Opponent,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
0,Alexander Isak,2024-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alexander Isak,2024-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alexander Isak,2024-08-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alexander Isak,2024-08-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alexander Isak,2024-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Alexander Isak,2025-05-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Alexander Isak,2025-05-25,Premier League,Everton,Y,"FW,LW",90.0,Home,L 0–1,90.0,90.0,L,FW,3.0
171,Alexander Isak,2025-05-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Alexander Isak,2025-05-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,Alexander Isak,2025-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
full_df["Minutes"] = full_df["Minutes"].fillna(0)
full_df = full_df.sort_values(["Player", "Date"])
full_df["Primary Position"] = full_df.groupby("Player")["Primary Position"].ffill()
full_df["Position Load Score"] = full_df.groupby("Player")["Position Load Score"].ffill()

In [58]:
full_df.head()

,Player,Date,Competition,Opponent,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score
0,Alexander Isak,2024-08-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alexander Isak,2024-08-03,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alexander Isak,2024-08-04,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alexander Isak,2024-08-07,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alexander Isak,2024-08-08,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
full_df["Injury"] = 0

for player, g in full_df.groupby("Player"):
    g = g.sort_values("Date")
    for i in range(1, len(g)):
        # Look back 7 calendar days
        current_date = g.iloc[i]["Date"]
        window = g[g["Date"] < current_date]
        window = window[window["Date"] >= current_date - pd.Timedelta(days=7)]
        rolling_minutes = window["Minutes"].sum()
        missed = g.iloc[i]["Minutes"] == 0
        if rolling_minutes > 200 and missed:
            full_df.loc[g.index[i], "Injury"] = 1

for player, g in full_df.groupby("Player"):
    g = g.sort_values("Date")
    for i in range(2, len(g)):
        m1 = g.iloc[i-2]
        m2 = g.iloc[i-1]
        m3 = g.iloc[i]
        if (
            (m1["Minutes"] > 75) and
            (m2["Minutes"] > 75) and
            (m3["Minutes"] == 0) and
            (m3["Date"] - m1["Date"]).days <= 8
        ):
            full_df.loc[g.index[i], "Injury"] = 1

In [90]:
full_df.head()

,Player,Date,Competition,Opponent,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score,Injury
0,Alexander Isak,2024-08-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Alexander Isak,2024-08-03,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Alexander Isak,2024-08-04,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Alexander Isak,2024-08-07,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Alexander Isak,2024-08-08,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [100]:
# ensure sorted by Player and Date
full_df = full_df.sort_values(["Player","Date"]).reset_index(drop=True)

rolling_vals = []
for player, grp in full_df.groupby("Player"):
    grp = grp.set_index("Date").sort_index()
    # this is an array of length grp.shape[0]
    roll7 = grp["Minutes"].rolling("7D").sum().values
    rolling_vals.extend(roll7)

full_df["7D Rolling Avg"] = rolling_vals

In [102]:
full_df

,Player,Date,Competition,Opponent,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score,Injury
0,Alexander Isak,2024-08-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0
1,Alexander Isak,2024-08-03,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0
2,Alexander Isak,2024-08-04,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0
3,Alexander Isak,2024-08-07,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0
4,Alexander Isak,2024-08-08,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,Youri Tielemans,2025-05-24,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,DM,4.0,0
2258,Youri Tielemans,2025-05-25,Premier League,Manchester Utd,N,DM,29.0,Away,L 0–2,29.0,29.0,L,DM,4.0,0
2259,Youri Tielemans,2025-05-28,NaN,NaN,NaN,NaN,0.0,NaN,NaN,29.0,29.0,NaN,DM,4.0,0
2260,Youri Tielemans,2025-05-29,NaN,NaN,NaN,NaN,0.0,NaN,NaN,29.0,29.0,NaN,DM,4.0,0
2261,Youri Tielemans,2025-05-31,NaN,NaN,NaN,NaN,0.0,NaN,NaN,29.0,29.0,NaN,DM,4.0,0

In [104]:
full_df.to_excel("Full_DF.xlsx")

In [106]:
full_df["Injury"] = 0

full_df.loc[(full_df["7D Rolling Avg"] >= 200) & (full_df["Minutes"] == 0), "Injury"] = 1

In [108]:
full_df["Injury"].value_counts()

Injury
0    2258
1       4
Name: count, dtype: int64

In [110]:
full_df.to_excel("Full_DF.xlsx",index=False)

In [7]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [9]:
full_df = pd.read_excel("Full_DF.xlsx",parse_dates=["Date"], date_format="%Y-%m-%d")

In [11]:
full_df

,Player,Date,Competition,Opponent,Started the Game,Position,Minutes,Venue,Result,7D Rolling Avg,14D Rolling Avg,Overall Result,Primary Position,Position Load Score,Injury
0,Alexander Isak,2024-08-01 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,NaN,0
1,Alexander Isak,2024-08-03 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,NaN,0
2,Alexander Isak,2024-08-04 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,NaN,0
3,Alexander Isak,2024-08-07 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,NaN,0
4,Alexander Isak,2024-08-08 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,Youri Tielemans,2025-05-24 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,NaN,DM,4.0,0
2258,Youri Tielemans,2025-05-25 00:00:00,Premier League,Manchester Utd,N,DM,29,Away,L 0–2,29,29,L,DM,4.0,0
2259,Youri Tielemans,2025-05-28 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,29,29,NaN,DM,4.0,0
2260,Youri Tielemans,2025-05-29 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,29,29,NaN,DM,4.0,0
2261,Youri Tielemans,2025-05-31 00:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,29,29,NaN,DM,4.0,0

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [6]:
def get_season(date):
    year = date.year
    if date.month >= 8:  # from August, new season starts
        return f"{year}_{str(year+1)[-2:]}"
    else:  # Jan–July belong to the previous season
        return f"{year-1}_{str(year)[-2:]}"

pos_load = {
     "GK":2, "DF":3, "MF":5, "FW":4
}

hi_comp = {"Premier League","Champions League","Europa League"}
def Comp_int(x):
    if x in hi_comp:
        return 5
    elif x == "FA Cup":
        return 4
    elif x == "EFL Cup" or x == "FA Community Shield":
        return 3
    else:
        return 1

def Pos_adjust(x):
    if x == "FW,MF":
        return "FW"
    elif x == "MF,FW":
        return "MF"
    elif x == "MF,DF":
        return "MF"
    elif x == "DF,MF":
        return "DF"
    elif x == "DF,FW":
        return "DF"
    elif x == "FW,DF":
        return "FW"
    else:
        return x

def fixture_5D_count(df):
    
    df = df.copy()
    rolling_counts = []
    for player, grp in df.groupby("Player"):
        grp = grp.set_index("Date").sort_index()
        # Count matches played in the last 5D (non-zero minutes)
        count5 = grp["Minutes"].gt(0).rolling("5D").sum().values  # .gt(0) = played match
        rolling_counts.extend(count5)
    df["FixtureCount_5D"] = rolling_counts
    return df

def rolling7D(df):
    df = df.copy()
    rolling_vals = []
    for player, grp in df.groupby("Player"):
        grp = grp.set_index("Date").sort_index()
        # this is an array of length grp.shape[0]
        roll7 = grp["Minutes"].rolling("7D").sum().values
        rolling_vals.extend(roll7)
    df["RollingAvg_7D"] = rolling_vals
    return df
	
def rolling14D(df):
    df = df.copy()
    rolling_vals = []
    for player, grp in df.groupby("Player"):
        grp = grp.set_index("Date").sort_index()
        # this is an array of length grp.shape[0]
        roll7 = grp["Minutes"].rolling("14D").sum().values
        rolling_vals.extend(roll7)
    df["RollingAvg_14D"] = rolling_vals
    return df

def age_band(age):
    if age <= 21:
        return "developing"
    elif age > 21 and age <=28:
        return "peak"
    elif age > 28 and age <=32:
        return "mature"
    else:
        return "decline"

def df_transform_v3(source):
    df = source.copy()
    df["Date"] = pd.to_datetime(df["Date"]) #validation

    span = df.groupby("Player")["Date"].agg(["min","max"]).reset_index()
    span.rename(columns={"min":"first_game","max":"last_game"}, inplace=True)

    # Collect team-level match dates
    team_dates = df["Date"].drop_duplicates().sort_values()

    # Build per-player calendar only for match dates within their span
    frames = []
    for row in span.itertuples(index=False):
        player = row.Player
        valid_dates = team_dates[(team_dates >= row.first_game) & (team_dates <= row.last_game)]
        cal = pd.DataFrame({"Player": player, "Date": valid_dates})
        frames.append(cal)
    calendar_df = pd.concat(frames, ignore_index=True)

    # Merge with source logs
    full_df = calendar_df.merge(df, on=["Player","Date"], how="left")

    # Fill
    full_df["Minutes"] = full_df["Minutes"].fillna(0)
    for col in ["Pos.","Team","Height(m)", "Weight(kg)", "Age"]:
        if col in full_df.columns:
            full_df[col] = full_df.groupby("Player")[col].ffill().bfill()

    full_df['Age'] = full_df['Age'].astype('int32')
    
    # Sort
    full_df = full_df.sort_values(["Player","Date"]).reset_index(drop=True)

    # Rolling features
    full_df = rolling14D(full_df)
    full_df = rolling7D(full_df)
    full_df = fixture_5D_count(full_df)
    full_df["FixtureCongestionFlag"] = full_df["FixtureCount_5D"] >= 2
    full_df["Age_Group"] = full_df["Age"].apply(age_band)

    # Position / Comp / Season
    if "Pos." in full_df.columns:
        full_df["PrimaryPosition"] = full_df["Pos."].apply(Pos_adjust)
        full_df["PositionLoadScore"] = full_df["Pos."].map(pos_load).fillna(3)
    if "Comp" in full_df.columns:
        full_df["CompIntensity"] = full_df["Comp"].apply(Comp_int)
    
    full_df["Season"] = full_df["Date"].apply(get_season)
    full_df['BMI'] = (full_df['Weight(kg)'] / (full_df['Height(m)']**2)).round(decimals=3)
    full_df["BMI_PosLoad"] = full_df["BMI"] * full_df["PositionLoadScore"]
    full_df["Age_Weight"] = np.exp(-((full_df["Age"] - 26)**2) / (2 * 5**2))
    return full_df

In [22]:
test = pd.read_csv("test.csv",parse_dates=["Date"], date_format="%d-%m-%Y")

In [23]:
test.dtypes

Player                object
Date          datetime64[ns]
Venue                 object
Team                  object
Opp                   object
Comp                  object
Result                object
Start                 object
Minutes                int64
Pos.                  object
Weight(kg)             int64
Height(m)            float64
Age                    int64
dtype: object

In [24]:
prepared_tbl = df_transform_v3(test)

In [25]:
prepared_tbl

,Player,Date,Venue,Team,Opp,Comp,Result,Start,Minutes,Pos.,...,FixtureCount_5D,FixtureCongestionFlag,Age_Group,PrimaryPosition,PositionLoadScore,CompIntensity,Season,BMI,BMI_PosLoad,Age_Weight
0,Aidan Borland,2024-09-24,Away,Aston Villa,Wycombe,EFL Cup,W 2-1,N,29.0,MF,...,1.0,False,developing,MF,5.0,3,2024_25,20.748,103.740,0.197899
1,Amadou Onana,2024-08-17,Away,Aston Villa,West Ham,Premier League,W 2-1,Y,90.0,MF,...,1.0,False,peak,MF,5.0,5,2024_25,19.987,99.935,0.726149
2,Amadou Onana,2024-08-24,Home,Aston Villa,Arsenal,Premier League,L 0-2,Y,75.0,MF,...,1.0,False,peak,MF,5.0,5,2024_25,19.987,99.935,0.726149
3,Amadou Onana,2024-08-31,Away,Aston Villa,Leicester City,Premier League,W 2-1,Y,60.0,MF,...,1.0,False,peak,MF,5.0,5,2024_25,19.987,99.935,0.726149
4,Amadou Onana,2024-09-14,Home,Aston Villa,Everton,Premier League,W 3-2,Y,45.0,MF,...,1.0,False,peak,MF,5.0,5,2024_25,19.987,99.935,0.726149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3673,Ãlex Moreno,2024-04-18,NaN,Aston Villa,NaN,NaN,NaN,NaN,0.0,DF,...,1.0,False,mature,DF,3.0,1,2023_24,21.223,63.669,0.726149
3674,Ãlex Moreno,2024-04-21,NaN,Aston Villa,NaN,NaN,NaN,NaN,0.0,DF,...,0.0,False,mature,DF,3.0,1,2023_24,21.223,63.669,0.726149
3675,Ãlex Moreno,2024-04-27,NaN,Aston Villa,NaN,NaN,NaN,NaN,0.0,DF,...,0.0,False,mature,DF,3.0,1,2023_24,21.223,63.669,0.726149
3676,Ãlex Moreno,2024-05-02,NaN,Aston Villa,NaN,NaN,NaN,NaN,0.0,DF,...,0.0,False,mature,DF,3.0,1,2023_24,21.223,63.669,0.726149
3677,Ãlex Moreno,2024-05-05,Away,Aston Villa,Brighton,Premier League,L 0-1,N,1.0,DF,...,1.0,False,mature,DF,3.0,5,2023_24,21.223,63.669,0.726149

In [27]:
prepared_tbl.dtypes

Player                           object
Date                     datetime64[ns]
Venue                            object
Team                             object
Opp                              object
Comp                             object
Result                           object
Start                            object
Minutes                         float64
Pos.                             object
Weight(kg)                      float64
Height(m)                       float64
Age                               int32
RollingAvg_14D                  float64
RollingAvg_7D                   float64
FixtureCount_5D                 float64
FixtureCongestionFlag              bool
Age_Group                        object
PrimaryPosition                  object
PositionLoadScore               float64
CompIntensity                     int64
Season                           object
BMI                             float64
BMI_PosLoad                     float64
Age_Weight                      float64
dtype: object